SegmentFault PacMan version 1.0
bme-kjit/bosch_ASDIIE pull request #13
Opened 2022-09-27 11:31 UTC by markbozsoki

@pier12 @szkLaszlo @oszilevi @czinegeandris

Elkészültünk a PacMan első verziójával. A **PacMan.py** script futtatásával indítható a program.

Az implementált funkcionalitások:
 - egy ízléses README.md megalkotása
 - PacMan irányítása (WDSA és 0123; restart és exit)
 - automatikus léptetés (játékállapot frissítés)
 - játék vége meghatározott számú lépés után
 - játék vége meghatározott idő után
 - pálya betöltése egy külső állományból (Map.dat)
 - pontgyűjtés (pontszám megjelenítés nélkül lett implementálva)
 - falak betöltés és interakciós logika

2022-09-30 13:25 UTC, szkLaszlo requested changes
szép megoldás, komplex design. Néhány apróbb komment van csak részemről, majd a többiek megmondják a tutit. Viszont a fontos a saját fájlok változtatása és a mi fájljaink békénhagyása 🗡️

2022-09-30 13:25 UTC, szkLaszlo commented on README.md
> +# bosch_ASDIIE SegmentFault
A mi fájljainkat nem szabadna változtatni. Légyszi revertáljátok ez a változást.

2022-09-30 13:25 UTC, szkLaszlo commented on .gitignore
> +/sample.py
Szintén nem változtatandó fájl. Legyen saját gitignore otok a saját mappátokban.

2022-09-30 13:25 UTC, szkLaszlo commented on SegmentFault/CodeProtocol.md
> +**SegmentFault coding protocol**
Nagyon jó ötlet, hogy ezt összefoglaltátok. 👏

2022-09-30 13:25 UTC, szkLaszlo commented on SegmentFault/MapData.py
> +        self.data_path = MapDataFilePath
Általában változók neve nem CamelCase hanem _ nal tagolt. De ez csak javaslat. Így osztály típusnak tűnik.

2022-09-30 13:25 UTC, szkLaszlo commented on SegmentFault/MapData.py
> +        while True:
Nekem úgy tűnik hogy a contains, get_size, get_first, get_coords függvények belső tartalmát lehetne egy read függvénnyel helyettesíteni, megfelelő paraméterezéssel. Kicsit kopi pészt, meg a fájl megnyitása is felesleges szerintem. Ha az initben betöltitek és elmentitek a mapdata részt akkor nem kell folyamatosan nyitogatni olvasgatni és while ciklusozgatni

2022-09-30 13:25 UTC, szkLaszlo commented on SegmentFault/PacMan.py
> +        # check for cherry (cherry is not implemented yet)
inkább #todo: t használjatok mint ilyen rough kommentet

2022-09-30 16:17 UTC, markbozsoki commented on README.md
> +# bosch_ASDIIE SegmentFault
@szkLaszlo Fixed

2022-09-30 16:17 UTC, markbozsoki commented on README.md
> +# bosch_ASDIIE SegmentFault
@szkLaszlo Fixed

2022-09-30 16:28 UTC, markbozsoki commented on .gitignore
> +/sample.py
@szkLaszlo Fixed
.gitignore hozzá lett adva a saját mappánkhoz

2022-09-30 16:29 UTC, markbozsoki commented on SegmentFault/CodeProtocol.md
> +**SegmentFault coding protocol**
❤️😄 köszönjük!

2022-09-30 16:30 UTC, markbozsoki commented on SegmentFault/MapData.py
> +        self.data_path = MapDataFilePath
@szkLaszlo Fixed

2022-09-30 16:30 UTC, markbozsoki commented on SegmentFault/PacMan.py
> +        # check for cherry (cherry is not implemented yet)
@szkLaszlo Fixed

2022-10-01 13:05 UTC, markbozsoki commented on SegmentFault/MapData.py
> +        while True:
@szkLaszlo 
A javaslatodnak megfelelően hozzá adtam az osztályhoz egy load_mapdata() függvényt. A fáljból beolvasott adatok a data_set nevű, lol(str) típusú változóban kerülnek eltárolásra. Ennek megfelelően módosítottam az osztály többi függvényét is.

2022-10-01 13:33 UTC, markbozsoki commented
@wolareklevente @Czeilinger96 @markb23 

Várjuk a review-kat!

Vasárnap estig tudnánk időt szánni az ajánlott változtatások implementására és hibajavításra.

Nagyon szépen kérlek titeket, hogy nézzétek át a kódunkat!
Ha segítségre van szükségetek pingeljetek minket teams-en.

Köszi

2022-10-02 15:56 UTC, Czeilinger96 commented on SegmentFault/TimerThread.py
> +        self._flag.clear()  # Set the flag false -> block the thread
Szerintem ilyenkor felesleges a komment, mert korábban már le van írva a funkciója.

2022-10-02 16:09 UTC, markbozsoki commented on SegmentFault/TimerThread.py
> +        self._flag.clear()  # Set the flag false -> block the thread
@Amontobix

2022-10-02 16:17 UTC, Czeilinger96 approved these changes
Nagyon igényes munka. Szerintem a kommentek jól leírják a funkciókat és világos, hogy mi mit csinál. Egyedül a TimerThread.py-ban vannak szerintem olyan kommentek, amik feleslegesek.

2022-10-02 16:47 UTC, kronos102 commented
Valóban igényes, komplex kód. Nagyon tetszik a map 'config file'-ból való megalkotása: ennél már csak az lett volna spécibb, ha a mintát követve olyan változókat is config file-ból olvastok be, mint a Commands billentyűbeállítása és egyéb, játékélményt befolyásoló paraméterek (pl.: timeout, max num of steps, etc.). Egyéb észrevételem nincs. Gratulálok a munkához!

2022-10-02 18:20 UTC, markbozsoki commented
> Valóban igényes, komplex kód. Nagyon tetszik a map 'config file'-ból való megalkotása: ennél már csak az lett volna spécibb, ha a mintát követve olyan változókat is config file-ból olvastok be, mint a Commands billentyűbeállítása és egyéb, játékélményt befolyásoló paraméterek (pl.: timeout, max num of steps, etc.). Egyéb észrevételem nincs. Gratulálok a munkához!

@kronos102  @Czeilinger96 
Köszönjük! 😄

Az irányítással kapcsolatos parancsok és egyéb játékmenetet érintő paraméterek külső fájlból való olvasását nem tartanám a legelőnyösebb megoldásnak. Mivel nem érdemes az általános felhasználóra/játékosra bízni a config fájlokban való "turkálást".
Valószínűleg lesz majd a játéknak egy menü rendszer kialakítva a következő fejlesztési fázisok valamelyikében és így a terminálon keresztül lesz megoldva a paraméterek személyre szabása. 🕹️ 

Ha nincs más észrevételed, kérlek "approve"-old a pull requestet.

2022-10-02 20:06 UTC, kronos102 approved these changes

2022-10-03 06:39 UTC, szkLaszlo commented on README.md
> +# bosch_ASDIIE SegmentFault
Ezt nekem kellene resolveolni ha elfogadom a fixed :D de nem baj

2022-10-03 06:44 UTC, szkLaszlo approved these changes
Részemről rendben van, már csak a többiek reviewjára van szükség. @wolareklevente @markb23

2022-10-03 06:44 UTC, szkLaszlo commented on SegmentFault/MapData.py
> +        """ Loads the mapdata from the file of the given path as numpy array
Menő, hogy a docstringet is átírtad, ez le szokott maradni.

2022-10-03 11:38 UTC, markb23 approved these changes

2022-10-03 11:41 UTC, wolareklevente approved these changes

2022-10-03 18:40 UTC, TerrorTegla approved these changes

2022-10-04 05:53 UTC, szkLaszlo commented
Csak egy kérdés, hogy ha minden megvan a mergehez miért nem történt meg? Még jó hogy jószívű vagyok :godmode:

2022-10-04 05:53 UTC, merged