I_NEED_A merge first 4 weeks
bme-kjit/bosch_ASDIIE pull request #14
Opened 2022-09-29 09:20 UTC by istvan-knab

Sziasztok! Elkészültünk a feladattal , várjuk az észrevételeiteket , miben lehetne még fejlődnie a kódunknak  .

@gujgidani @4doschris

2022-09-29 09:37 UTC, szkLaszlo requested changes
Első blickre  a .idea mappa nem kell a repoba. Az gitignoreba valo :) minden saját kódotok saját mappában legyen ami a team name.

2022-09-29 09:38 UTC, szkLaszlo commented
Hozzá kéne adni a reviewereket meg az assignee kat is. Az előbbi a reviewer csapat, az assignee meg a ti csapattagotok

2022-09-29 16:22 UTC, istvan-knab reviewed
Megcsináltam a gitignoret ,  mappába raktam a szükséges dolgokat a csapat nevéve

2022-09-30 13:36 UTC, szkLaszlo requested changes
Néhány kommentem van, de alapból szép megoldás, a többiek majd kiegészítik ;)

2022-09-30 13:36 UTC, szkLaszlo commented on .gitignore
> +.idea
ez még kevés lesz :D a gitignore legyen a saját mappátokban és a .idea fájlt le kell törölni a branchről hogy működjön.
A mi gitignorunkat pedig nem kellene változtatni.

2022-09-30 13:36 UTC, szkLaszlo commented on I_NEED_A/pacman_env.py
> +    def first_step(self):
Szerintem erre nincs szükség. A resetbe be lehet rakni hogy self.step_ = 100, illetve az initbe.

2022-09-30 13:36 UTC, szkLaszlo commented on I_NEED_A/pacman_env.py
> +
Itt felesleges az y=y sor, de az összes irány függvényben van hasonló. Illetve a sok felesleges entert is kivehetitek, csak nő a sorszám de hozzáadott értéke nincs

2022-09-30 13:36 UTC, szkLaszlo commented on I_NEED_A/pacman_env.py
> +        for _ in range(num):
Ez szerintem inkább egy while kéne legyen. Így ha véletlenül a self.body koordinátát sorsoljuk ki, rögtön egyel kevesebb object lesz.

2022-09-30 13:36 UTC, szkLaszlo commented on I_NEED_A/pacman_env.py
> +def initialize_parameters():
Erre miért van szükség? Nem lehetnek osztály változók? a mainben kellene definiálni ezeket szerintem.  A global használata nem a legjobb praktika

2022-09-30 13:36 UTC, szkLaszlo commented on I_NEED_A/pacman_env.py
> +        print("control assist TODO")
??

2022-09-30 13:36 UTC, szkLaszlo commented on I_NEED_A/pacman_env.py
> +        if done_==True:
A done_ az egy bool, nincs szükség az ==True ra.

2022-09-30 18:41 UTC, gujgidani requested changes
@istvan-knab @TothAron @TerrorTegla I finished my review. I hope it will help to make your code better.

2022-09-30 18:41 UTC, gujgidani commented on I_NEED_A/pacman_env.py
> +# Team : I_NEED_A
I think these pieces of information are redundant, because we can get them from Version Control.

2022-09-30 18:41 UTC, gujgidani commented on I_NEED_A/pacman_env.py
> +        self.time_step = 40
This variable isn't used anywhere in the code. I suggest to remove it.

2022-09-30 18:41 UTC, gujgidani commented on I_NEED_A/pacman_env.py
> +            print(f"Score {self.score}")
I think it would be better to use exceptions (like ValueError) instead of return codes there.

2022-09-30 18:41 UTC, gujgidani commented on I_NEED_A/pacman_env.py
> +        self.objects = []
In my opinion, it would be better to specify the objects in the variable's name (like coins etc.), because we might use different objects (like ghosts) in the later stage of game development.

2022-09-30 22:45 UTC, benceuveges requested changes
I didn't comment those parts reviewed by others, only found this as extra. It can help simplify the code.

2022-09-30 22:45 UTC, benceuveges commented on I_NEED_A/pacman_env.py
> +        info= None
If it is not used, it can be removed in my opinion. There is no need to pass NoneType data to the observation.

2022-10-01 08:59 UTC, istvan-knab commented on I_NEED_A/pacman_env.py
> +        info= None
The return parameters are like by every step function of gym environments . In most cases is this variable not used , but it's always given as return parameter . If I don't give value for this variable , the code wont't run .  ------>Its used as return parameter .

2022-10-01 09:00 UTC, istvan-knab commented on I_NEED_A/pacman_env.py
> +        info= None
Some gym environments : https://www.gymlibrary.dev/#

2022-10-01 09:42 UTC, istvan-knab commented on I_NEED_A/pacman_env.py
> +        info= None
@benceuveges

2022-10-01 10:51 UTC, istvan-knab commented on I_NEED_A/pacman_env.py
> +def initialize_parameters():
A main jobb olvashatósága érdekében szerveztem ki egy függvénybe ezeket a változókat , így szerintem átláthatóbb . amennyiben szükséges , persze lehetnek osztályváltozók is .

2022-10-01 10:58 UTC, istvan-knab commented on I_NEED_A/pacman_env.py
> +        print("control assist TODO")
Valóban elfelejtettem , leírásnak szántam , hogy melyik gomb mit csinál , ezt javítottam .

2022-10-01 11:04 UTC, istvan-knab commented on I_NEED_A/pacman_env.py
> +        self.objects = []
Solved

2022-10-01 11:10 UTC, istvan-knab commented on I_NEED_A/pacman_env.py
> +        self.time_step = 40
Solved

2022-10-01 11:11 UTC, istvan-knab commented on I_NEED_A/pacman_env.py
> +# Team : I_NEED_A
Solved

2022-10-01 11:32 UTC, istvan-knab commented on I_NEED_A/pacman_env.py
> +
Köszönöm  , javítva.

2022-10-01 11:32 UTC, istvan-knab commented on I_NEED_A/pacman_env.py
> +            print(f"Score {self.score}")
Solved

2022-10-01 11:34 UTC, istvan-knab commented
@benceuveges @gujgidani megnéztem a javaslataitokat , amit lehetett kijavítottam . @szkLaszlo már párat megcsináltam , még rajta vagyunk .

2022-10-01 11:35 UTC, istvan-knab commented
@4doschris ránéznél a kódunkra , mit kéne még javítani?

2022-10-01 11:37 UTC, istvan-knab commented on I_NEED_A/pacman_env.py
> +def initialize_parameters():
Megoldottam

2022-10-01 18:21 UTC, TerrorTegla commented on I_NEED_A/pacman_env.py
> +        for _ in range(num):
kijavítottam

2022-10-02 09:56 UTC, zuborxyz commented
@istvan-knab Szia! Légy szíves adj hozzá engem is, mint reviewer!

2022-10-02 11:16 UTC, istvan-knab commented
@4doschris @zuborxyz várjuk a javaslatokat , hogy legyen még időnk javítani . Ha nem találtok semmit ,  azt is írjátok  .

2022-10-02 12:22 UTC, zuborxyz approved these changes
Found only non-critical typos, good job!

2022-10-02 12:22 UTC, zuborxyz commented on I_NEED_A/pacman_env.py
> +                raise TypeError("Only integers brtween 0 and 3 are accepted")
Typo in error string: between.

2022-10-02 12:22 UTC, zuborxyz commented on I_NEED_A/pacman_env.py
> +        print("0->done  1->right    2->up   3->left")
I think you meant to write 0->down.

2022-10-02 13:09 UTC, istvan-knab commented on I_NEED_A/pacman_env.py
> +        print("0->done  1->right    2->up   3->left")
Solved

2022-10-02 13:09 UTC, istvan-knab commented on I_NEED_A/pacman_env.py
> +                raise TypeError("Only integers brtween 0 and 3 are accepted")
Solved

2022-10-02 13:30 UTC, benceuveges approved these changes
Részemről rendben van, a felvetett dologok orvosolva lettek, kérdések megválaszolva. Szép kód @istvan-knab @TerrorTegla @TothAron

2022-10-02 16:15 UTC, gujgidani approved these changes
A kért módosítások kijavításra kerültek, a játék működik, a kódolás érthető.
Részemről megfelelő a kód.
Szép munka, gratula hozzá! 😉

2022-10-02 16:48 UTC, TothAron commented on .gitignore
> +.idea
Outdated (also solved).

2022-10-02 17:02 UTC, TothAron commented on I_NEED_A/pacman_env.py
> +    def first_step(self):
Tényleg redundáns volt a self.step_ = 100 a first_step() föggvényben. Az érintett rendundáns rész refaktorálásra került.

2022-10-03 06:19 UTC, istvan-knab commented
Köszönjük az eddigi észrevételeket és az alapos munkát @gujgidani @zuborxyz @benceuveges  , tényleg segített a jobb és érthetőbb kód létrehozásában . @4doschris szívesen vennénk a javaslataidat , hogy még jobb lehessen a kód az ötleteiddel ;). @szkLaszlo megcsináltunk mindent amit kértél , remélem így gondoltad .

2022-10-03 06:33 UTC, 4doschris commented
> Köszönjük az eddigi észrevételeket és az alapos munkát @gujgidani @zuborxyz @benceuveges  , tényleg segített a jobb és érthetőbb kód létrehozásában . @4doschris szívesen vennénk a javaslataidat , hogy még jobb lehessen a kód az ötleteiddel ;). @szkLaszlo megcsináltunk mindent amit kértél , remélem így gondoltad . 

@istvan-knab Természetesen, ma, időben igyekszem végignézni, már elkezdtem.

2022-10-03 06:48 UTC, szkLaszlo requested changes
A .idea mappa még mindig létezik ebben a PRban. Addig nem fogom elfogadni :D Ha nem megy, segítek a törlésben.

2022-10-03 06:48 UTC, szkLaszlo commented on I_NEED_A/pacman_env.py
> +            if action != 0 or action != 1 or action != 2 or action != 3:
Csak egy javaslat: ```if action not in range(0,4): ```

2022-10-03 12:13 UTC, istvan-knab commented
> A .idea mappa még mindig létezik ebben a PRban. Addig nem fogom elfogadni :D Ha nem megy, segítek a törlésben.


Megcsináltam, elvileg most màr jók vagyunk😁 @szkLaszlo

2022-10-03 13:51 UTC, 4doschris reviewed
Csekkoltam, bár a többiek már jóval megelőztek. Szép kód, szépen kommentelve. Így tovább! 👏🏻

2022-10-03 17:03 UTC, 4doschris approved these changes
Szép munka, hajrá a továbbiakban is! ;)

2022-10-03 17:05 UTC, merged