AgiliTEAM's Pac-Man stage #1
bme-kjit/bosch_ASDIIE pull request #15
Opened 2022-09-30 04:46 UTC by BPelenczei

@sardif @bme-kjit  @szkLaszlo @oszilevi @czinegeandris @glaju @peterdlakatos @pier12

Sziasztok!

Elkészültünk a Pac-Man első verziójával, várjuk az észrevételeiteket!

Implementált funkciók:

- Readme
- üres map falak nélkül
- pacman mozgatása 4 irányba
- pontok gyűjtése
- játék terminálása adott lépésszám után

2022-09-30 20:24 UTC, BPelenczei commented on AgiliTEAM/pacman_env.py
> +MAP_SIZE = 30
Igazad van, javítottam. Pontosabban áttettem a konstruktor argumentumába def value-val őket.

2022-09-30 20:30 UTC, BPelenczei commented on README.md
> +# bosch_ASDIIE Bosch Team
Így van, nem sync-eltük a forkot pr előtt, de ha minden igaz, már ez is ki lett javítva. Viszont a readme alján nem tudom, hogy miért jelez source diff-et a git... ha átváltok rich diff-re akkor 'no visible changes here' üzenet. Esetleg ebben tudnál segíteni @szkLaszlo ?

2022-09-30 20:31 UTC, BPelenczei commented on AgiliTEAM/pacman_env.py
> +        # Only for RL purposes
Javítva és köszi, hogy írtad! Eddig nem tudtam erről a TODO comment feature-ről...

2022-09-30 20:39 UTC, BPelenczei commented
@szkLaszlo
Szia,
A fent megjelölt issue-kat orvosoltam, esetleg majd rá tudnál nézni mégegyszer?
Köszi szépen előre is!

2022-10-02 12:33 UTC, sardif commented on AgiliTEAM/pacman_env.py
> +        return state
Könnyen olvasható és logikus kód, szóval én nem látok változtatni valót :D

2022-10-02 12:38 UTC, BPelenczei commented on AgiliTEAM/pacman_env.py
> +        return state
@sardif 
köszi szépen!
esetleg akkor megtennéd, hogy resolve-olod ezt az issue-t és approve-olod a PR-t, ha tényleg nincs semmi? :)

2022-10-02 13:40 UTC, BPelenczei commented
@sardif
Ne lezárd a PR-t hanem approve-old. :) Elvileg ahol a review felület van, ott lenyitod a "review changes" gombot és ki lehet választani, hogy needs changes/approve/comment.

2022-10-02 14:00 UTC, sardif approved these changes

2022-10-03 06:54 UTC, szkLaszlo commented on README.md
> +# bosch_ASDIIE Bosch Team
Valszeg ilyen LF meg CRLF különbségek vannak. de maradhat. Nem történt érdembeli változás

2022-10-03 06:57 UTC, szkLaszlo approved these changes
A PR rendben van szép munka @BPelenczei, ugyanakkor felhívnám a csapattagok figyelmét, hogy az 1 és 0 commit a 117 ből elég kevésnek tűnik. Nem annyira arányos a munkaelosztás, hát milyen csapatmunka ez? De szerencsére ezen még tudtok változtatni a jövőbeli PRokon. @NyesteAmbrusPal @VitayVanda

2022-10-03 08:10 UTC, istvan-knab requested changes
Szép  a kód , clean kódjából nem találtam benne hibát   . Logikus a függvények szervezése , a docstring és a typehint is mindenhol sokat segít a kód megértésében . A változónevek megválasztása tökéletes , jól érthető a kód kommentstruktúra nélkül is.

2022-10-03 08:26 UTC, BPelenczei commented
@istvan-knab 

Szia!

Köszi a reviewt és a szép szavakat!
A kommentelt issue-t orvosoltam, illetve re-requesteltem a reviewt, ha lesz időd, légyszíves nézz rá, hogy megfelel-e a javítás.

2022-10-03 08:58 UTC, istvan-knab approved these changes
Gyémánt 💠 Pont erre gondoltam , így már hibátlan ;)

2022-10-03 17:45 UTC, gujgidani approved these changes
A kód rendkívül részletes, mégsem tartalmaz felesleges részeket. A kommentek, Docstring-ek, Typehint-ek és a megfelelő elnevezések használata nagyban megkönnyíti a megértését annak, hogy mi történik a kódban, akár egy kezdő felhasználó számára is. Minden cselekvés külön függvénybe került kiszervezésre, ahol lehetőség volt rá. Végül pedig a legfontosabb, hogy a kód működőképes. 😄 
Ezen szempontok miatt nem tudok kifogást találni a kódban, sem működési, sem Clean Coding szempontból.
Igényes, szép munka, gratulálok hozzá! 😁

2022-10-04 05:52 UTC, merged