TeamSix Pacman Milestone 1
bme-kjit/bosch_ASDIIE pull request #16
Opened 2022-09-30 17:37 UTC by DEW211

@leonsuszter @markbozsoki @origergelylaszlo 
@szkLaszlo 

Pacman milestone 1

Elnézést a késésért.
A coin generáló függvényünk szerintem roppant érdekesre sikerült. Kíváncsi vagyok a véleményetekre.

2022-09-30 18:21 UTC, markbozsoki commented
Sziasztok!
@DEW211 @holloaron @dadam356 

Királyok vagytok! 👑
Teljesen időben is vagytok. 😄

Jól néz ki a kód első ránézésre, viszont egy két meglátásom lenne így az elején.
 * (Érdemes lett volna mergelni a **main** ágba és azzal megnyitni a pull request-et.)
 * Sokat segítene nekünk (és agilisabb is lenne), ha fel lennének kommentelve a függvények.
 
 
***A kommentek nélkül nem fogjuk tudni tovább engedni a kódot.***

2022-09-30 18:35 UTC, markbozsoki requested changes

2022-09-30 18:35 UTC, markbozsoki commented on README.md
> +# bosch_ASDIIE Bosch Team
Azt kérték, hogy ez a fálj ne változzon.
REVERT

2022-09-30 18:35 UTC, markbozsoki commented on TeamSix/pacman.py
> +import pygame
Kommentek legyenek a függvényekhez.

2022-09-30 18:35 UTC, markbozsoki commented on TeamSix/pacman.py
> +
Kicsit nehezíti a kód olvashatóságát, hogy a változók és a függvények ugyanolyan stílusban vannak.
A függvények lehetnének például *CamelCase* formában.

2022-09-30 18:56 UTC, markbozsoki commented
Kipróbáltam a progit.
Nagyon jól néz ki! És tök ötletes a coin-ok elhelyezése. 😃 

Viszont:
  * Van 6 db error a program indításakor az *ALSA* lib-től.
  * Nem vagyok benne biztos, hogy az előző pont hatására, de elszáll a terminál és nem lehet kilépni a programból indítás után.
  * A játéktér el van csúszva az ablak bal felső sarkába, így vannak coinok amik nem gyűjthetők össze.
  * Hiányolom az adott eltelt másodperc utáni leállást.
  
***Az ALSA lib error-oknak mindenképp nézzetek utána.***

2022-09-30 19:53 UTC, Amontobix requested changes
Az a  kód részlet amit reviewra kaptam számomra jól olvasható kifejező változó és függvény nevekkel. 

-**Ami fontos:** A kommentelés az osztályoknál és a metódusoknál hiányos, kérlek pótoljátok ezeket. 
- Pacman class step metódusában a felfele és a balra mozgásra nincs ellenőrzés hogy az a koordi valid-e, és szerintem kellene. Ezt kérlek, nézzétek meg. 

Ami észrevétel még és csak formalitás:  
- Szerintem "SOLID-osabb" lenne a kód, ha nem lennének a konstansok globális változók hanem valahol külön lennének szedve pl.: enumba

2022-09-30 19:53 UTC, Amontobix commented on TeamSix/pacman.py
> +
Szerintem a kapott pozíció felfele és balra mozgás esetén is ellenőrizendő kéne hogy legyen. Pygame-nél a bal felső sarok a (0,0) pont, ha jól emlékszem, így negatív számokra is szükség lehet ellenőrzésre.

2022-09-30 19:53 UTC, Amontobix commented on TeamSix/pacman.py
> +
Valamint a kommentelés hiányos

2022-09-30 19:53 UTC, Amontobix commented on TeamSix/pacman.py
> +
kommentelés hiányos, pótoljátok kérlek

2022-09-30 19:53 UTC, Amontobix commented on TeamSix/pacman.py
> +            self.direction = POSITION_RIGHT
kommentelés hiányos, pótoljátok kérlek

2022-09-30 19:53 UTC, Amontobix commented on TeamSix/pacman.py
> +
Coins class kommentelése hiányos, pótoljátok kérlek

2022-10-01 09:56 UTC, DEW211 commented
> Kipróbáltam a progit. Nagyon jól néz ki! És tök ötletes a coin-ok elhelyezése. 😃
> 
> Viszont:
> 
> * Van 6 db error a program indításakor az _ALSA_ lib-től.
> * Nem vagyok benne biztos, hogy az előző pont hatására, de elszáll a terminál és nem lehet kilépni a programból indítás után.
> * A játéktér el van csúszva az ablak bal felső sarkába, így vannak coinok amik nem gyűjthetők össze.
> * Hiányolom az adott eltelt másodperc utáni leállást.
> 
> _**Az ALSA lib error-oknak mindenképp nézzetek utána.**_

@markbozsoki 
- ALSA errorokat javítottam, ez meg kell javítsa az instabil terminál állapotot is, de azt nem tudtam reprodukálni.
- Játéktér elcsúszás javítva
- Mostmár megáll a játék 100 lépés után

2022-10-01 10:10 UTC, DEW211 commented on TeamSix/pacman.py
> +
A nemnagativitást tulajdonképpen ellenőriztük azoknál az irányoknál. Ami kimaradt, hogy pacman elfér-e a (0, 0) ponton (ezért vontuk le a lépés méretét a másik kettő irányban)

2022-10-01 11:46 UTC, markbozsoki commented
> > Kipróbáltam a progit. Nagyon jól néz ki! És tök ötletes a coin-ok elhelyezése. 😃
> > Viszont:
> > 
> > * Van 6 db error a program indításakor az _ALSA_ lib-től.
> > * Nem vagyok benne biztos, hogy az előző pont hatására, de elszáll a terminál és nem lehet kilépni a programból indítás után.
> > * A játéktér el van csúszva az ablak bal felső sarkába, így vannak coinok amik nem gyűjthetők össze.
> > * Hiányolom az adott eltelt másodperc utáni leállást.
> > 
> > _**Az ALSA lib error-oknak mindenképp nézzetek utána.**_
> 
> @markbozsoki
> 
> * ALSA errorokat javítottam, ez meg kell javítsa az instabil terminál állapotot is, de azt nem tudtam reprodukálni.
> * Játéktér elcsúszás javítva
> * Mostmár megáll a játék 100 lépés után

Remek! @DEW211
Megnéztem így szerintem már jó lesz, eltűntek az error-ok és a terminal sem száll el. 😄

Bár a feladat specifikációja egy időzítőről szól és nem a megtett lépések számáról.
De ennek a hiánynak a mérlegelését inkább rábíznám @szkLaszlo-ra.

2022-10-01 14:11 UTC, markbozsoki requested changes
A README.md-ben legyen visszaírva "Bosch Team"- re
Egészítsétek ki a kódot kommentekkel.

2022-10-01 18:06 UTC, leonsuszter requested changes

2022-10-01 18:06 UTC, leonsuszter commented on TeamSix/pacman.py
> +
A teljes osztályon belül kérnék kommenteket, megmagyarázva a funkciókat és kicsit jobban tagolná is a műveleteket.

2022-10-01 18:06 UTC, leonsuszter commented on TeamSix/pacman.py
> +    game.play()
Ha már az előző kódrészletek is meg vannak magyarázva a kommentekkel, akkor ezt az elvet tartva ide is kommentelném az entry point-ot

2022-10-02 11:22 UTC, origergelylaszlo reviewed
Szép, átlátható a kód és elegáns a megvalósítás. Összesen két változtatási javaslatom lenne, amit a kódhoz kommentekbe írtam.

2022-10-02 11:22 UTC, origergelylaszlo commented on TeamSix/pacman.py
> +POSITION_UP = 'UP'
Tetszik, hogy a konstans változók uppercase-ek, és ez kiemeli őket a kódból.

2022-10-02 11:22 UTC, origergelylaszlo commented on TeamSix/pacman.py
> +    def change_direction(self):
Ahogy látom, itt a self.direction mindig a self.new_direction értékét kapja meg. Ha ez igaz, akkor egy sorban is elég:
`self.direction=self.new_direction`

2022-10-02 13:07 UTC, holloaron commented on README.md
> +# bosch_ASDIIE Bosch Team
@markbozsoki 
Javítva!

2022-10-02 13:26 UTC, markbozsoki commented on README.md
> +# bosch_ASDIIE Bosch Team
@holloaron
nem a megfelelő readme lett módosítva

2022-10-02 13:38 UTC, holloaron commented on README.md
> +# bosch_ASDIIE Bosch Team
@markbozsoki 
valóban, köszi, javítva

2022-10-02 13:55 UTC, markbozsoki commented on README.md
> +# bosch_ASDIIE Bosch Team
@holloaron 
Valami még mindig nem jó
A "TeamSix" mappán kívüli README fájl legyen visszaállítva az eredeti állapotra
Ahogy ez megtörténik, ez a fájl el is fog tűnni a "ChangedFile" fül alól, mert technikailag nem történt benne változás

2022-10-02 17:08 UTC, holloaron commented on TeamSix/pacman.py
> +
Azért használtuk így, mert minél egyszerűbb megoldást kerestünk, illetve így hatékonyabban is fut a program

2022-10-02 17:09 UTC, holloaron commented on TeamSix/pacman.py
> +    def change_direction(self):
Köszi, módosítottam!

2022-10-02 17:13 UTC, holloaron commented on TeamSix/pacman.py
> +    game.play()
Szerintem nem kell mindenhova kommentet írni, csak hogy legyen. Ami egyértelmű funkció azt nem érdemes megmagyarázni. Előadáson is azt javasolták, hogy csak oda kommenteljünk ahova tényleg kell.

2022-10-02 17:14 UTC, holloaron commented
Sziasztok!
@markbozsoki @Amontobix @leonsuszter 

Tettünk kommenteket, megnézitek, hogy így megfelelő-e?

2022-10-02 17:18 UTC, holloaron commented on TeamSix/pacman.py
> +
Elvben @dadam356  elvégezte a kért változtatásokat. Szóljatok ha még hiányoltok valamit!

2022-10-02 17:37 UTC, holloaron commented on TeamSix/pacman.py
> +
Minden irányba ellenőrizve volt a mozgás, csak más feltételek szükségesek. Kommentekkel kiegészítve remélem már érthető.

2022-10-02 17:44 UTC, holloaron commented on TeamSix/pacman.py
> +
Pótolva

2022-10-02 17:44 UTC, holloaron commented on TeamSix/pacman.py
> +            self.direction = POSITION_RIGHT
Pótolva

2022-10-02 17:44 UTC, holloaron commented on TeamSix/pacman.py
> +
Pótolva

2022-10-02 17:45 UTC, holloaron commented on TeamSix/pacman.py
> +import pygame
Pótolva

2022-10-02 19:22 UTC, markbozsoki approved these changes

2022-10-02 21:19 UTC, Amontobix approved these changes
Részemről a kódot megfelelőnek találom, a kért változtatások még a hétvégén el lettek végezve, ezért külön köszönet 😄

2022-10-03 05:29 UTC, origergelylaszlo approved these changes

2022-10-03 07:59 UTC, szkLaszlo approved these changes
Egy két kommentet hagytam, de amúgy szép megoldás. Részemről rendben van. A felépítés kicsit máshogy csináltam volna alapból, de ez egyéni preferencia. Az időzítős működés pedig félig igaz, jó lesz így 👍 A lényeg, hogy lépni tudjunk és menjen a játék.

2022-10-03 07:59 UTC, szkLaszlo commented on TeamSix/pacman.py
> +class Constants(Enum):
Van e valami hozzáadott értéke ennek hogy osztály? Lehetne constants = {} és feltöltve a key value értékekkel. Így megspórolnátok a .value részt minden hívásnál. De csak javaslat kérdés, hogy miért jobb ez?

2022-10-03 07:59 UTC, szkLaszlo commented on TeamSix/pacman.py
> +    def generate(self):
Nekem jobban tetszene, ha a generate függvénynek lenne bemenete, ami megmondja hogy hány coint generáljunk. Így modulárisabb és bármikor lehet újat, pl ha egyet megeszik a helyére másikat, stb

2022-10-03 07:59 UTC, szkLaszlo commented on TeamSix/pacman.py
> +        while len(self.positions) < self.number_of_coins:
Szép kis logika lett itt kitalálva 💯

2022-10-03 15:03 UTC, leonsuszter approved these changes

2022-10-03 18:42 UTC, DEW211 commented on TeamSix/pacman.py
> +class Constants(Enum):
Ebben az alakban szerintem nem jobb. A Constants['value'].value, vagyis valami amit random stringekkel indexelünk, nem sokkal jobb mint egy string

2022-10-03 18:50 UTC, merged