Git-egylet Pacman first sprint
bme-kjit/bosch_ASDIIE pull request #17
Opened 2022-10-01 23:20 UTC by gujgidani

Sziasztok! 
Elkészültünk az első sprint feladataival. Az észrevételeket, javaslatokat szívesen látjuk, hogy jobbá tehessük a kódunkat.
Előre is köszönjük a segítséget ebben! (és a türelmet, hogy csak a határidőhöz közel tudtuk leadni a PR-t 😄 ) 

@bme-kjit @szkLaszlo @BPelenczei @NyesteAmbrusPal @VitayVanda

2022-10-02 08:35 UTC, BPelenczei requested changes
@gujgidani @4doschris @benceuveges 

Sziasztok!

Átnéztem a kódot, nagyjából rendben van minden, észrevételeimet/javaslataimat kommentekben megtaláljátok. Nagyrészt szépséghibáról van szó, kivéve egyet, a move függvényben tesztelés közben találtam egy bug-ot.
Ha bármi kérdés van, tag-eljetek be, vagy keressetek Teams-en.

All in all, szép munka! 👍

2022-10-02 08:35 UTC, BPelenczei commented on Git-egylet/pacman.py
> +    def _move(self, pos_x: int, pos_y: int, action: int):
Ennél a függvénynél nincs levédve az x, y koordináták increment/decrement-je: egyrészt Index errort lehet elérni ha az array méretével megegyező lesz a koordináta, másrészt (ami kevésbé szerencsés) a numpy-ban van negatív indexelés, amikor hátulról éred el az elemeket pl:
 ```
arr = np.array([2, 4, 6])
print(arr[-2])
```
--> 4-et fog kiírni.

Úgy jöttem rá, hogy nem kaptam pontot a felvett pellet-ért (mert (-3, -3) volt a pacman koordinátája)... :)

2022-10-02 08:35 UTC, BPelenczei commented on Git-egylet/pacman.py
> +        print("Your score: {env.score}")
Nem jó a szintaktika, azt írja ki, hogy `Your score: {env.score}`
```suggestion
        print("Your score: {0}".format(env.score))
```

2022-10-02 08:35 UTC, BPelenczei commented on Git-egylet/pacman.py
> +    print("Final score: {env.score}")
Szintén, amit egyel fentebb írtam.

2022-10-02 08:35 UTC, BPelenczei commented on Git-egylet/pacman.py
> +    def _change_direction(self, action: int):
Mivel nincs a class instance-ére vonatkozó változó, lehetne staticmethod is.
```suggestion
    @staticmethod
    def _change_direction(action: int):
```

2022-10-02 08:35 UTC, BPelenczei commented on Git-egylet/pacman.py
> +    def _up(self, pos_x: int, pos_y: int):
Szintén, amit egyel fentebb írtam.
@staticmethod mind a négy irányú move function.

2022-10-02 08:35 UTC, BPelenczei commented on Git-egylet/pacman.py
> +        self.create_pellets(10)
Magic number, célszerű lenne ennek egy class variable, amit a konstruktorban adtok meg.
```suggestion
        self.create_pellets(self.num_pellets)
```

2022-10-02 08:35 UTC, BPelenczei commented on Git-egylet/pacman.py
> +        # map initialization
Szerintem itt sem szükségesek kommentek, redundáns információt hordoznak.
```suggestion

```

2022-10-02 15:54 UTC, gujgidani commented on Git-egylet/pacman.py
> +    def reset(self):
Solved

2022-10-02 15:54 UTC, gujgidani commented on Git-egylet/pacman.py
> +        self.show_window_size = 300
Solved

2022-10-02 15:54 UTC, gujgidani commented on Git-egylet/pacman.py
> +        done = False
Solved

2022-10-02 15:54 UTC, gujgidani commented on Git-egylet/pacman.py
> +        self.max_steps = 200
Solved

2022-10-02 15:54 UTC, gujgidani commented on Git-egylet/pacman.py
> +        # get the current PacMan position
Solved

2022-10-02 15:54 UTC, gujgidani commented on Git-egylet/pacman.py
> +            return False
Solved

2022-10-02 15:55 UTC, gujgidani commented on Git-egylet/pacman.py
> +    def _move(self, pos_x: int, pos_y: int, action: int):
Solved

2022-10-02 15:55 UTC, gujgidani commented on Git-egylet/pacman.py
> +        print("Your score: {env.score}")
Solved

2022-10-02 15:55 UTC, gujgidani commented on Git-egylet/pacman.py
> +    print("Final score: {env.score}")
Solved

2022-10-02 15:55 UTC, gujgidani commented on Git-egylet/pacman.py
> +    def _change_direction(self, action: int):
Solved

2022-10-02 15:56 UTC, gujgidani commented on Git-egylet/pacman.py
> +    def _up(self, pos_x: int, pos_y: int):
A módosításokkal végül nem lett egyik sem static, de:
Solved 😄

2022-10-02 15:56 UTC, gujgidani commented on Git-egylet/pacman.py
> +        self.create_pellets(10)
Solved

2022-10-02 15:56 UTC, gujgidani commented on Git-egylet/pacman.py
> +        # map initialization
Solved

2022-10-02 16:02 UTC, gujgidani commented
@BPelenczei 
Végeztem az említett észrevételek áttekintésével, a hibák kijavításával.
Köszönjük szépen az átfogó elemzést és a hasznos tippeket, számomra sok újdonság is volt benne, amire magamtól nem is gondoltam volna. 😄 
Kérlek, nézd át újra, hogy a javítások megfelelőek-e.
@NyesteAmbrusPal @VitayVanda @bme-kjit @szkLaszlo 
Tőletek is szívesen várjuk az észrevételeket, javítási ötleteket 😁

2022-10-02 17:38 UTC, BPelenczei requested changes
@gujgidani @4doschris @benceuveges 

Sziasztok!

Második review körömmel is végeztem, először is: szép munka, congrats az eddigi javításokra!
Így másodjára is kommenteltem egy keveset, de ezek már tényleg aprócska szépséghibák, viszont az önmagát (kommentekkel) magyarázó kódsorokra becopyzom az órai ppt két mondatát, sztem tök jól leírja, hogy hogyan kéne ezeket használni.
```"Every comment is written to compensate for a failure. First try to clean the code, then if you fail, comment."```

2022-10-02 17:38 UTC, BPelenczei commented on Git-egylet/pacman.py
> +        self.num_pellets = 10
Ez is mehetne konstruktor argumentumba, ahogy a többi amit tök jól csináltál!
```suggestion
        self.num_pellets = num_pellets
```

2022-10-02 17:38 UTC, BPelenczei commented on Git-egylet/pacman.py
> +        # add pellets
Szerintem itt se szükséges komment a megértéshez (feltétlen).
```suggestion

```

2022-10-02 17:38 UTC, BPelenczei commented on Git-egylet/pacman.py
> +        # add Pacman
Ugyanaz, mint amit egyel fentebb írtam.
```suggestion

```

2022-10-02 17:38 UTC, BPelenczei commented on Git-egylet/pacman.py
> +        # rescale the image
Note: ez nem issue, csak komment, lezárhatod, amint elolvastad :)

A fentiekkel ellentétben itt szerintem azért érdemes kommentet használni, mert nem feltétlen látod első ránézésre, hogy ez a két-három kódsor mit csinál. Kicsit iskola példa, mert igazából ez se annyira megfejthetetlen, de remélem érted, mit szeretnék ezzel mondani.

2022-10-02 17:38 UTC, BPelenczei commented on Git-egylet/pacman.py
> +        self.num_pellets = 10
A konstruktorban már megjegyeztem, azt kijavítva pedig úgyis elő fog jönni. Nem szükséges neki mindig értéket adni szerintem, csak a konstruktor argumentumaként.
```suggestion

```

2022-10-02 18:30 UTC, gujgidani commented on Git-egylet/pacman.py
> +        self.num_pellets = 10
Solved

2022-10-02 18:31 UTC, gujgidani commented on Git-egylet/pacman.py
> +        # add pellets
Solved

2022-10-02 18:31 UTC, gujgidani commented on Git-egylet/pacman.py
> +        # add Pacman
Solved

2022-10-02 18:31 UTC, gujgidani commented on Git-egylet/pacman.py
> +        self.num_pellets = 10
Solved

2022-10-02 18:33 UTC, gujgidani commented
@BPelenczei Elvégeztem a második review-ban javasolt módosításokat is. Ha esetleg találsz még valamit, bátran jelezd felénk. 😁

2022-10-02 19:10 UTC, BPelenczei approved these changes
@gujgidani @4doschris @benceuveges 

Sziasztok!

Köszönöm szépen az együttműködést, így harmadjára mindent rendben találtam, a kérdéseimet megválaszoltátok, issue-kat megoldottátok - resolve-oltam is őket.
Így részemről a kód további módosítást nem igényel, approved.

**_Good job!_**

2022-10-03 08:08 UTC, szkLaszlo approved these changes
Nem nagyon tudok hozzászólni. Szép kód, jól kommentelt.

2022-10-03 08:08 UTC, szkLaszlo commented on Git-egylet/README.md
> +
Tegyétek bele azért a negyedik embert is :D hátha a jövőben kontributál majd, ugye @zuborxyz

2022-10-03 12:00 UTC, NyesteAmbrusPal commented on Git-egylet/pacman.py
> +        x, y = self._move(pos_x, pos_y, action)
I would rather use self.body within the function, since it is a member variable of the class, therefore the functions of the class can also access it -> it does not need to be the input parameter of the _move function

2022-10-03 12:00 UTC, NyesteAmbrusPal commented on Git-egylet/pacman.py
> +        return x, y
According to my comment above, I would use only 1 input parameter also.

2022-10-03 12:00 UTC, NyesteAmbrusPal commented on Git-egylet/pacman.py
> +            raise ValueError("Please choose an action between 0-3")
Maybe just print out some warning, we do not want to exit the game when we misstyped something (just use previous action)

2022-10-03 16:24 UTC, benceuveges commented on Git-egylet/README.md
> +
Hozzáadtam @zuborxyz kollégát @szkLaszlo

2022-10-03 17:10 UTC, gujgidani commented on Git-egylet/pacman.py
> +        x, y = self._move(pos_x, pos_y, action)
Solved

2022-10-03 17:10 UTC, gujgidani commented on Git-egylet/pacman.py
> +        return x, y
Solved

2022-10-03 17:14 UTC, gujgidani commented on Git-egylet/pacman.py
> +            raise ValueError("Please choose an action between 0-3")
Ezzel kapcsolatban a 3-ik, Clean Code-os előadás egyik diájára tudok hivatkozni, amit mellékelek képként is.
![Error handling](https://user-images.githubusercontent.com/102506112/193637975-e420a6ff-9ca7-47ff-bfa0-761fa9249b8b.png)
Ehhez viszonyodva a print helyett a PPT szerinti "tisztább" megoldást választottam, emiatt ezen a kódrészleten nem szeretnék módosítani.

2022-10-03 17:16 UTC, gujgidani commented
@NyesteAmbrusPal a javaslatokat átnéztem, ahol kellett, javítottam. Kérlek, nézd át újra, hogy megfelelőek-e a javítások és az indoklások.

2022-10-03 17:55 UTC, VitayVanda approved these changes
Úgy látom hogy előttem a többiek minden hibára rámutattak már.
Szép munkát végeztetek!

2022-10-03 18:01 UTC, NyesteAmbrusPal approved these changes

2022-10-03 18:17 UTC, istvan-knab requested changes
Clean Code szempontjából jónak találtam , működőképes jól olvasható kód . Ezen az egy változtatáson kívül én nem találtam benne olyan dolgot , ami miatt nehéz lett volna a kódot olvasni  .   Mindenhol megvolt a bemenő adatok és a kimenők typehint-je , a docstringek nagyrészt jó magyarázatot adnak a jól szervezett függvényekre . Jól tördelt kód , kommentelése érthető .

2022-10-03 18:17 UTC, istvan-knab commented on Git-egylet/pacman.py
> +        self.body = [0, 0]
Itt könnyítené a kód megértését ha a body paramétereit a docstringben leírnád , melyik a függőleges és melyik a vízszintes.

2022-10-03 18:28 UTC, gujgidani commented on Git-egylet/pacman.py
> +        self.body = [0, 0]
Solved

2022-10-03 18:29 UTC, istvan-knab approved these changes
Köszi , nagyon szép munka lett 🚀

2022-10-03 19:57 UTC, merged