Development
bme-kjit/bosch_ASDIIE pull request #18
Opened 2022-10-01 23:59 UTC by sardif

@holloaron @DEW211 @dadam356

Sziasztok megnyitottam a pull request-et, kérlek nézzétek át a progit.

2022-10-02 15:58 UTC, holloaron commented
Szia, köszi szépen! 
@sardif 

Elég nehéz összetenni a pacman mozgását ebben a formában, de olvastam a kommented, megértem. A jövőben én azért mepróbálnám valahogy megoldani a megjelenítést. Persze ha az egészet egyedül kellett megcsináld, akkor nem voltál egyszerű helyzetben,

2022-10-02 16:01 UTC, holloaron commented on pacman.py
> +# Note: I've seen this visualizing method in the code of team Namco. It is useful for me because my computer can't handle the opening window for some
A Note vége lemaradt véletlen

2022-10-02 16:09 UTC, sardif commented
@szkLaszlo @oszilevi @czinegeandris
Sziasztok,
Most vettem észre, hogy 5 ember approve-ja szükséges, így a minket review-zó csapaton felül kérlek ti is nézzétek át.

2022-10-02 16:17 UTC, holloaron requested changes

2022-10-02 16:17 UTC, holloaron commented on pacman.py
> +# Note: I've seen this visualizing method in the code of team Namco. It is useful for me because my computer can't handle the opening window for some
A note vége lemaradt véletlen

2022-10-02 16:17 UTC, holloaron commented on pacman.py
> +    def __init__(self, map_size, num_of_food, max_step):
A függvényekhez typehint legyen használva, illetve a docstring-nek is vannak saját formázása, az "Args" kellene a function parameters helyett például. A clean code-os ppt-ben van mindkettő dologra helyes példa.
Ezt a két dolgot minden függvénynél ahol van bemenő paraméter, meg kellene csinálni, de csak ide fogom odaírni.

2022-10-02 16:17 UTC, holloaron commented on pacman.py
> +    num_of_food = int(input("How many food would you like on the map? "))
Én itt megadnék egy javasolt tartományt mindkét paraméterre, mert így nem igazán lehet előre látni, hogy mi fog kiférni a képernyőre.

2022-10-02 17:07 UTC, dadam356 commented on pacman.py
> +                 max_step=100)
A max_step értékét lehet jobb lenne egy változóval megadni.

2022-10-02 18:53 UTC, sardif commented on pacman.py
> +    num_of_food = int(input("How many food would you like on the map? "))
Jogos felvetés, ezt javítottam is. Holnap átírom a függvény kommenteket is

2022-10-02 18:54 UTC, sardif commented on pacman.py
> +                 max_step=100)
Még nem teljesen értem, hogy mire gondolsz. El tudnád magyarázni részletesebben kérlek?

2022-10-02 19:24 UTC, DEW211 commented on pacman.py
> +                 max_step=100)
Ami a gondolat volt, hogy egy kicsit magic number "szaga" lehet így. Ki lehet menteni egy konstansba, de nekem nincs rá szükségem.

2022-10-02 19:45 UTC, dadam356 commented on pacman.py
> +                 max_step=100)
Igen erre gondoltam. Létre lehetne hozni egy konstans változót, aminek az értéke 100, és ezt használni.

2022-10-02 20:16 UTC, DEW211 requested changes

2022-10-02 20:24 UTC, DEW211 commented
Egy funkció hiányzik. Pacman kis időközönként nem lép. A Git diasorban megtaláljátok a funkciók listáját. 
Kicsit aggódok az inputot kezelő megoldásotok miatt. Az eredeti játékban pacman automatán lépked az adott irányba amíg tud, nem vár inputra minden lépés után. Ha implementáljátok ezt a funkciót a mostani megoldás mellé, akkor nehéz lesz inputot kérnetek és a terminál folyton frissülni fog ami az ablak vibrálásához vezethet.

2022-10-03 08:12 UTC, szkLaszlo commented on pacman.py
> +                 max_step=100)
szerintem itt maradhat mert ez egy default érték beállítás. A docstringben legyen benne és jó lesz. Olyanokra szükséges a constant amik rendesen értékadások a kódban indokolatlanul.

2022-10-03 08:23 UTC, szkLaszlo requested changes
A kollégák általi kommenteket meg kell oldani, de alapvetően a docstringek hiányát leszámítva részemről rendben. Ezeket csináld meg légyszi

2022-10-03 15:07 UTC, sardif commented on pacman.py
> +    def new_position_of_pacman(self, pressed_key: str):
Cserélve igére: move_pacman

2022-10-03 15:08 UTC, sardif commented on pacman.py
> +    def eating_food(self):
Valóban a többi helyen nem használtam -ing-et. Javítva itt is.

2022-10-03 15:08 UTC, sardif commented on pacman.py
> +                 max_step=100)
Ezt akkor így hagyom.

2022-10-03 15:57 UTC, sardif commented on pacman.py
> +    def __init__(self, map_size, num_of_food, max_step):
Ezeket meg csináltam.

2022-10-03 15:58 UTC, sardif commented on pacman.py
> +    # In this function I printed the actual step into the terminal
Elkészítettem a docstringeket

2022-10-03 15:59 UTC, sardif commented on pacman.py
> +    # In this function I calculated the new position of the map and check if any food is eaten
Törölve

2022-10-03 16:20 UTC, sardif commented on pacman.py
> +        elif pressed_key == 'q':
Kiszedtem q-t.

2022-10-03 18:16 UTC, sardif commented on README.md
> +# bosch_ASDIIE_TSzBF
Javítottam.

2022-10-03 18:36 UTC, sardif commented
@holloaron @DEW211 @dadam356 @szkLaszlo
Sziasztok!
Kijavítottam a request-eket. Tudnátok approve-olni kérlek?

2022-10-03 19:07 UTC, dadam356 approved these changes

2022-10-03 20:22 UTC, holloaron approved these changes

2022-10-03 20:27 UTC, DEW211 approved these changes

2022-10-04 05:49 UTC, szkLaszlo approved these changes

2022-10-04 05:50 UTC, merged