PacMan
bme-kjit/bosch_ASDIIE pull request #22
Opened 2022-10-18 13:34 UTC by Czeilinger96

2022-10-18 13:37 UTC, AkosScherer approved these changes
Tetszik!

2022-10-21 09:16 UTC, szkLaszlo requested changes
A kódot a többiek reviewzzák majd. Kicsit átírtam a reviewer és assignee részt. Az assigneehoz még a csapattagjaidat tedd be légyszi és mindenki próbáljon meg beszállni a javításokba. 
Más: Az idea mappát törölni kéne a repóból, és a saját munkát egy csapatnév mappába áthelyezni. Ezután ebben hozz létre egy gitignoret és hozzá kell adni az idea mappát.

2022-10-21 09:17 UTC, szkLaszlo commented
> Tetszik!

Elég véleményes review! Próbáld újra ;)

2022-10-22 12:37 UTC, Kurtiadam commented on Pybranch/pacman.py
> +game_over_pos_y = 500
Ha ezek is konstansok, akkor ezek a nevek is legyenek az előzőek szerint formázva szerintem.

2022-10-22 12:40 UTC, Kurtiadam commented on Pybranch/pacman.py
> +class DOT(pygame.sprite.Sprite):
Osztálynév, ezért így írnám: Dot

2022-10-22 12:59 UTC, Kurtiadam commented on Pybranch/pacman.py
> +    FramePerSec.tick(FPS)
Ezeknek a while ciklusban kellene lenniük, hogy rendesen fusson a program.

2022-10-22 13:16 UTC, Kurtiadam commented on Pybranch/pacman.py
> +    Pac_man = Player()
A program elején deklarált konstansokat szerintem inkább a példányosításnál argumentumonként kellene megadni, pl:
Pac_man = Player(STARTING_POS_X = 160, STARTING_POS_Y = 520, stb.)

2022-10-22 13:18 UTC, Kurtiadam commented on Pybranch/pacman.py
> +        Score_Dot = DOT()
Itt is a példányosítás paramétereiről szóló probléma, amit fentebb írtam.

2022-10-22 13:22 UTC, Kurtiadam requested changes
Sziasztok,
nagyon jó lett ez a pygame-es megoldás, remekül néz ki és fut a program. 
Néhány észrevétel:

1. Hiányzik a megadott idő utáni program leállás (ami az egyik feladatpont volt), viszont a max pontszám megszerzése utáni leállás implementálva van, ez is megfelelő? @szkLaszlo 
2. Hiányoznak a type hintek és docstringek.
3. Néhány helyen nem konzisztensek a névadási formátumok ezeket jelöltem a kódban.
4. A program elején deklarált konstansokat inkább az osztályok példányosításnál kellene paraméterként megadni szerintem.

Ezeken kívül szerintem szép munka lett! :)

2022-10-27 10:53 UTC, bme-kjit commented
@Buxi527bme @farkas-peter megnéznétek a PRt? már csak a ti reviewtokra vár a csapat.

2022-11-04 13:57 UTC, farkas-peter requested changes
Szép munka, könnyen olvasható és érthető kód! Külön plusz pont, hogy nem csak favágó módjára nekiálltatok az implementálásnak, hanem kerestetek direkt ilyen célokra már korábban megírt pygame parancsokat és azokkal egyszerűsítettétek a fejlesztést.

Néhány észrevétel (hasonlóan Ádám megjegyzéseihez):
- A sok global változó helyett az egyes paramétereket be lehetne vinni a megfelelő osztályokba
- Szerintem lehetne egy megjelenítésért felelős osztály is, ami kicsit rendszerezi az oda kapcsolódó részeket/paramétereket
- A docstringek és typingok hiányoznak.

(U.i.: Elnézést a késői review-ért!)

2022-11-04 13:57 UTC, farkas-peter commented on Pybranch/pacman.py
> +class Player(pygame.sprite.Sprite):
Talán a PacMan elnevezés egyértelműbb lenne, ha már a pontok is Dot-ok lettek, valamint amikor példányosításra kerül az osztály, akkor ott is Pac_man-ként lesz elnevezve. De ez csak apróság, lehet csak én gondolom így :D

2022-11-04 13:57 UTC, farkas-peter commented on Pybranch/pacman.py
> +    def move(self):
Hiányzik a docstring és a typing

2022-11-04 13:57 UTC, farkas-peter commented on Pybranch/pacman.py
> +PACMAN_SPEED = 5
Ezek lehetnének a Player osztály változói

2022-11-04 13:57 UTC, farkas-peter commented on Pybranch/pacman.py
> +MAX_SCORE = 60
Ezek lehetnének a Dot osztály változói

2022-11-04 13:57 UTC, farkas-peter commented on Pybranch/pacman.py
> +    all_sprites.add(Pac_man)
A Dot osztály egy függvényben elvégezhetné a megadott számú objektumok generálását.

2022-11-04 13:57 UTC, farkas-peter commented on Pybranch/pacman.py
> +GAME_OVER_POS_Y = 500
Ezek is lehetnének rendre a Player vagy egy megjelenítésért felelős osztály/függvény változói.

2022-11-04 13:57 UTC, farkas-peter commented on Pybranch/pacman.py
> +        DISPLAYSURF.blit(current_time, (TIME_POS, SCORE_POS))
Lehetne egy megjelenítésért felelős osztály, amely összefogná ezeket a renderrel kapcsolatos parancsokat

2022-11-04 13:57 UTC, farkas-peter commented on Pybranch/pacman.py
> +        all_sprites.draw(DISPLAYSURF)
Lehetne a Player vagy a Dot osztály része

2022-11-05 17:01 UTC, Buxi527bme approved these changes
Nekem is kifejezetten tetszik, hogy nem a legegyszerűbb irányt vettétek és szépen pygame-ben raktátok össze, az is tetszik hogy vizualitásban is egy fokkal többet megtettetek mint ami elvárt volt.
 Az észrevételeim:

- Talán kicsit kevés a comment, bár azon is múlik, hogy nem kifejezetten értek a pygame-hez
- Tudom, már kétszer olvastátok, de a változók helyeit Farkas Péter commentjei szerint akár gondoljátok át az átláthatóság kedvéért

Ezek mellett jól strukturált és szép munka, gratu!

2022-11-07 09:14 UTC, Kurtiadam approved these changes

2022-11-11 13:31 UTC, szkLaszlo reviewed
A repó readmején ne változtassunk légyszi. Csak a saját mappában lévőn

2022-11-11 13:32 UTC, szkLaszlo approved these changes

2022-11-11 13:32 UTC, merged