I_NEED_A 2nd sprint (solid_version) 🚀
bme-kjit/bosch_ASDIIE pull request #26
Opened 2022-11-07 22:06 UTC by TothAron

Done: 
 - solid version implemented
 - refactor done on test codes
 - code is running

2022-11-08 19:23 UTC, istvan-knab commented
@kronos102 @markb23 @Czeilinger96 @wolareklevente  nyílt a PR , várjuk az észrevételeiteket. 😃

2022-11-10 16:59 UTC, istvan-knab commented
@wolareklevente @markb23 @kronos102 @Czeilinger96 várjuk a visszajelzést , légyszi nézzetek rá a kódra.

2022-11-11 14:42 UTC, istvan-knab commented
Megkapjátok az üzeneteket? Nagyon szeretnénk haladni a dologgal , és csak miattatok nem tudunk 4 napja semmit csinálni. Légyszi ha nem érdekel a dolog akkor legalább approveoljátok , vagy írjatok annyit hogy látjátok .

2022-11-11 15:47 UTC, Czeilinger96 commented
Igen, megkapom az üzeneteket. Azt jól értem, hogy most csak a mozgás van meg?

2022-11-11 16:11 UTC, markb23 approved these changes

2022-11-11 20:15 UTC, Czeilinger96 commented
Le tudjátok írni, hogy hogyan kellene futtatni?

2022-11-11 21:22 UTC, istvan-knab commented
> Igen, megkapom az üzeneteket. Azt jól értem, hogy most csak a mozgás van meg?

Csao ! Nem , a térkép szélén a falak is implementálva vannak már.

2022-11-11 21:23 UTC, istvan-knab commented
> Le tudjátok írni, hogy hogyan kellene futtatni?

A run.py-t kéne futtatni.

2022-11-12 13:01 UTC, Czeilinger96 commented
> > Igen, megkapom az üzeneteket. Azt jól értem, hogy most csak a mozgás van meg?
> 
> Csao ! Nem , a térkép szélén a falak is implementálva vannak már.

Tehát, akkor a a game over feature is hiányzik, meg a falak a pálya belsejében. Meg az első sprintnek a dolgait nem kell, hogy tudja a program?

2022-11-13 14:59 UTC, istvan-knab commented
@kronos102 @wolareklevente ?? Lassan nem marad időnk.

2022-11-13 15:06 UTC, istvan-knab commented
> > > Igen, megkapom az üzeneteket. Azt jól értem, hogy most csak a mozgás van meg?
> > 
> > 
> > Csao ! Nem , a térkép szélén a falak is implementálva vannak már.
> 
> Tehát, akkor a a game over feature is hiányzik, meg a falak a pálya belsejében. Meg az első sprintnek a dolgait nem kell, hogy tudja a program?

Game over megoldva

2022-11-14 10:50 UTC, szkLaszlo requested changes

2022-11-14 10:50 UTC, szkLaszlo commented on I_NEED_A/pacman_env.py
> +        while _<range(num):
Ez elég csúnya. Működik egyáltalán? Jobban preferálom a for -t ha véges számú futtatás van.

2022-11-14 10:50 UTC, szkLaszlo commented on I_NEED_A/pacman_env.py
> +        while _<range(num):
vagy ugye ```while len(self.coins) < num```

2022-11-14 10:50 UTC, szkLaszlo commented on I_NEED_A/pacman_solid/Objects/core/pacman.py
> +    def wall_limit(self, coordinates: Coordinates):
Ezt meg lehetne hívni a return nél az előző függvényben. Mert akkor nem kell még külön a pacmanben.

2022-11-14 10:50 UTC, szkLaszlo commented on I_NEED_A/pacman_solid/Objects/test/test_something.py
> +"""Test script for (something)."""
???

2022-11-14 10:50 UTC, szkLaszlo commented on I_NEED_A/pacman_solid/main.py
> +import curses
ennek így van létjogosultsága?

2022-11-14 22:22 UTC, istvan-knab commented on I_NEED_A/pacman_solid/Objects/test/test_something.py
> +"""Test script for (something)."""
Ide még lesz implementálva kód , sajnos az idő szűkében nem került rá sor.

2022-11-14 22:22 UTC, istvan-knab commented on I_NEED_A/pacman_solid/main.py
> +import curses
Nem , ez a file valóban nem kell

2022-11-14 22:50 UTC, istvan-knab commented on I_NEED_A/pacman_solid/Objects/core/pacman.py
> +    def wall_limit(self, coordinates: Coordinates):
Ezt nem teljesen értem most hogyan kéne.

2022-11-14 22:50 UTC, istvan-knab commented on I_NEED_A/pacman_solid/Objects/core/pacman.py
> +    def wall_limit(self, coordinates: Coordinates):
Ezt nem teljesen értem most mit kéne változtatni rajta.

2022-11-14 23:10 UTC, istvan-knab commented
Kedves reviewerek ! Hála nektek , nem tudtuk beadni a munkánkat. Sajnos ez most így alakult , amennyiben erre később lesz lehetőség , másokkal ne szúrjatok ki ennyire . 
@wolareklevente @kronos102 

Üdv : Isti

2022-11-15 06:47 UTC, gujgidani approved these changes
Sziasztok!

"Vész-reviewerként", így merge határidőhöz felettébb közel túl mélyen már nem volt időm teljes mélységeiben átnézni a kódot, csak az alábbi szempontok szerint vizsgálni azt:
- A funkciók megléte, a kód futása
- SOLID alapelvek betartása
- Tesztek megléte és működése
- Korábbi sprint szempontjai (pl. Clean Code)

Ezeket figyelembe véve az alábbiak az észrevételeim:
A kód fut, feature-ök közül megvan benne az oldalsó fal és a game over. Nyilván ezt még bőven ki lehetne egészíteni, de nem ilyen közel a merge határidőhöz. 😅 
A SOLID alapelvek be lettek tartva, az egyes modulok 1 dologért felelnek, a szükséges interface-ek megvannak. A tesztek megvannak és működnek is. Clean coding szempontjából lehet, hogy jól jött volna még pár függvény megértéséhez 1-1 docstring.

Ezen kisebb hibák ellenére, mivel a megírt funkciók jól működnek, a közeli határidőt figyelembe véve el tudom fogadni a PR-t.

2022-11-15 11:30 UTC, Czeilinger96 approved these changes
Sziasztok,

a SOLID-nak megfelel. Pár funkció hiányzik. Illetve egy kicsit több magyarázat lehetne, hogy mi mit csinál.

2022-11-15 12:02 UTC, istvan-knab commented
> Sziasztok,
> 
> a SOLID-nak megfelel. Pár funkció hiányzik. Illetve egy kicsit több magyarázat lehetne, hogy mi mit csinál.

Köszönjük szépen , az elfogadás ellenére ezeket a hibákat a későbbiekben még javítani fogjuk .

2022-11-17 18:52 UTC, BPelenczei requested changes
@TothAron @istvan-knab 

Sziasztok!

Lehúztam, átnéztem, kommenteltem a repotokat, ez alapján a következő általános sorokat tudom leírni:

- SOLID elveknek megfelel, megfelelő struktúrájú a kód
- elég sok helyen hiányoznak a függvények docstringjei, typehintjei, kérlek ezeket orvosoljátok
- a testek megfelelő mennyisége és minősége megvan, viszont kicsit manuálisan működnek. jót tenne nekik egy lib (pl unittest) alkalmazása
- bizonyos funkciók (belső falak, halál) még nem állnak rendelkezésre, legyetek szívesek ezt is pótolni.

Alapvetően szép munka, hajrá hajrá a továbbiakban!

Üdv,
Bálint

2022-11-17 18:52 UTC, BPelenczei commented on I_NEED_A/pacman_solid/pacman_run.py
> +from Objects.core.get_action import KeyEvent
felesleges import, törölhető lenne mert nem használja semmi
```suggestion

```

2022-11-17 18:52 UTC, BPelenczei commented on I_NEED_A/pacman_solid/Objects/core/pacman.py
> +        return True
Itt ugye mindig True-val tér vissza a függvény, emiatt a pacman-ünk örök életű lesz :)
szóval majd légyszi itt gondoljátok át, hogy a halált mint feature-t hogyan integráljátok a játékba.

2022-11-19 08:41 UTC, istvan-knab commented on I_NEED_A/pacman_solid/pacman_run.py
> +from Objects.core.get_action import KeyEvent
Solved

2022-11-19 08:42 UTC, istvan-knab commented on I_NEED_A/pacman_solid/pacman_run.py
> +    args = arg_parser.parse_args()
Megoldva , a benne maradt TODO commentet is töröltem.

2022-11-19 08:52 UTC, istvan-knab commented on I_NEED_A/pacman_solid/Objects/core/pacman.py
> +        return True
Megoldottam , bevezettem egy osztályváltozót , amit folyamatosan csökkent minden egyes esemény során , valamint az elért 0 érték esetén False értékkel tér vissza.

2022-11-19 08:52 UTC, istvan-knab commented on I_NEED_A/pacman_solid/Objects/core/pacman.py
> +            limited_x = max(1, min(coordinates.row, self.map_size.row_num))
@TothAron légyszi ezt csináld meg te

2022-11-19 08:53 UTC, istvan-knab commented on I_NEED_A/pacman_solid/Objects/test/test_pacman_game_state.py
> +
@TothAron ezt légyszi csináld meg

2022-11-20 22:19 UTC, TothAron commented on I_NEED_A/pacman_solid/Objects/test/test_something.py
> +"""Test script for (something)."""
Ez csak esetleges plusz tesztnek volt fenntartva, más funckiókat fontosabbnak találtunk (falak, pacman food) ezeket implementáltuk ebben a PR-ban.

2022-11-20 22:20 UTC, TothAron commented on I_NEED_A/pacman_solid/Objects/core/pacman.py
> +    def wall_limit(self, coordinates: Coordinates):
Az implementált pálya és falak hatására ez egyszerűbb és szebb lett. Köszi a reviewt!

2022-11-20 22:23 UTC, TothAron commented on I_NEED_A/pacman_solid/Objects/core/pacman.py
> +            limited_x = max(1, min(coordinates.row, self.map_size.row_num))
Implementálva lett rendes map, illetve falak. Ez a függvény is egyértelműbb lett. Köszi az észrevételt!

2022-11-20 23:00 UTC, TothAron commented on I_NEED_A/pacman_env.py
> +        while _<range(num):
Ez már nincs benne.

2022-11-20 23:02 UTC, TothAron commented on I_NEED_A/pacman_solid/Objects/test/test_pacman_game_state.py
> +
Kész. A futtatása: 
`pip install pytest`
`python -m pytest Objects\test\test_pacman_visualization.py`

2022-11-20 23:10 UTC, BPelenczei commented
@TothAron @istvan-knab 
Sziasztok, csekkoltam a javítást, sikerült mindent kijavítanotok amit kértem, szép munka!

Üdv,
Bálint

2022-11-20 23:11 UTC, BPelenczei approved these changes

2022-11-20 23:11 UTC, merged