TeamSix solid sprint
bme-kjit/bosch_ASDIIE pull request #28
Opened 2022-11-08 13:13 UTC by DEW211

Solid Pacman első nekifutás

2022-11-14 10:27 UTC, Kurtiadam commented on TeamSix/solid_version/maze.py
> +        return pacman
Én itt a Pacman melletti jobb oldali blokkot is üresre állítanám, hogy esetleges ottani falgenerálásnál Pacman ne haljon meg rögtön.

2022-11-14 10:27 UTC, Kurtiadam requested changes
Sziasztok!

Tökre jól néz ki a játék, jól is fut. A kért feladatokat szépen teljesítettétek. A kódbázis elég SOLID-nak tűnik, viszont a **unit testek** hiányoznak, ha jól látom.
Illetve egy apró megjegyzést még tennék a játék mechanikájával kapcsolatosan: Van, amikor indításnál Pacman haladási irányában éppen elé generál egy falat a játék és egy másodperc töredéke alatt meg is hal így Pacman, ezt én orvosolnám, de nem nagy hiba.
Egyébként szép munka! :)

2022-11-14 10:41 UTC, szkLaszlo reviewed
Az én részem rendben van. Megvárjuk a többiek reviewját és akkor mehet az approve :)

2022-11-14 21:07 UTC, farkas-peter requested changes
Sziasztok!

Nagyon szép munka, szerintem sikerült teljesíteni a SOLID elveket. Szép, rendezett és átlátható a kód, logikus felépítéssel. Beszédes változó neveket használtatok, mellyel nagy mértékben megkönnyítettétek a megértést.

Néhány észrevételem van csak:
- Pár docstring és typing hiányzik, esetleg érdemes lenne őket pótolni, hogy még egyszerűbb legyen megérteni mit csinál egy egy függvény.
- A konstansok kezelése számomra nem mindenhol egyértelmű. Amiket nem a constants enumban adtatok meg, azokat miért vettétek külön? (De lehet csak nekem nem jött át a mögöttes gondolatmenet.)

2022-11-14 21:38 UTC, DEW211 commented
> Sziasztok!
> 
> Nagyon szép munka, szerintem sikerült teljesíteni a SOLID elveket. Szép, rendezett és átlátható a kód, logikus felépítéssel. Beszédes változó neveket használtatok, mellyel nagy mértékben megkönnyítettétek a megértést.
> 
> Néhány észrevételem van csak:
> 
> * Pár docstring és typing hiányzik, esetleg érdemes lenne őket pótolni, hogy még egyszerűbb legyen megérteni mit csinál egy egy függvény.
> * A konstansok kezelése számomra nem mindenhol egyértelmű. Amiket nem a constants enumban adtatok meg, azokat miért vettétek külön? (De lehet csak nekem nem jött át a mögöttes gondolatmenet.)

@farkas-peter A Constants osztályt próbáltam globális tulajdonságokra használni (pl. méretek), ahol csak lokálisan kellett megoldás, azokat nem raktam bele.(pl. Field-ben a dicitonary -- mondjuk ez pont nem tetszik, utólag ránézve)

2022-11-14 21:39 UTC, DEW211 commented
@Kurtiadam Adtam unit teszteket pár osztályra.

2022-11-14 22:20 UTC, farkas-peter approved these changes

2022-11-15 08:39 UTC, szkLaszlo approved these changes
Részemről rendben. A többieket megnézzük

2022-11-15 08:50 UTC, Kurtiadam approved these changes
Szép munka!

2022-11-15 15:04 UTC, Buxi527bme approved these changes
Hali!

Látványos lett, túl is szárnyalja az elvárásokat. Véleményem szerint minden principle-nek megfelel a munkátok, szépen lett felbontva minden class ahogyan azt kell. Viszont  kommentek tényleg hiányoznak néhány helyről.

Szuper lett!

2022-11-16 07:48 UTC, markbozsoki requested changes
Átnézve a kódot jónak tűnik
Viszont legalább az osztályoknak legyen docstring-je és a typehint-ek is legyenek minden függvénynél.

Kicsit nagy a káosz a fáljok között. Jó lenne, ha a különböző funkcionalitású  modulok külön mappákba kerülnének valamilyen átlátható logika alapján.
Pl.:
az interface-ek kerüljenek a [solid_version/interfaces] mappába
az Enum-ok kerüljenek a [solid_version/enums] mappába

Nem tudom mi az a "thing".
Figyeljetek arra, hogy beszédesek legyenek az elnevezések

2022-11-16 07:48 UTC, markbozsoki commented on TeamSix/solid_version/coin.py
> +class Coin(Thing):
docstringeket és hiányolom
Legalább az osztályhoz legyen valami rövid leírás
(ez vonatkozik a többi osztályra is)

2022-11-16 07:48 UTC, markbozsoki commented on TeamSix/solid_version/thing.py
> +class Thing(Drawable, Steppable):
Lehetne sokkal beszédesebb az elnevezése ennek a modulnak
Alapvetően kerülném a thing, something, other stb szavak használatát mert nem mondanak el semmit arról, hogy mi is ez valójában
(+docstring)

2022-11-16 07:48 UTC, markbozsoki commented on TeamSix/solid_version/coin_holder.py
> +        self.things = []
a things micsoda?
legyen beszédesebb az elevezése
ha más osztályban is van ilyen kérlek azt is javítsátok
(+docstring)

2022-11-16 07:48 UTC, markbozsoki commented on TeamSix/solid_version/field.py
> +        self.things = []
legyen beszédesebb az elnevezés
Mi az a thing?

2022-11-20 16:35 UTC, markbozsoki approved these changes

2022-11-20 16:36 UTC, merged