Namco 2nd sprint: SOLID version of PacMan with wall features
bme-kjit/bosch_ASDIIE pull request #29
Opened 2022-11-08 13:19 UTC by farkas-peter

Ebben a sprintben implementáltuk a falakat megvalósító funkciókat, valamint refaktoráltuk a kódbázist, hogy megfeleljenek a SOLID elveknek.

Várjuk az észrevételeket és javaslatokat.

Előre is köszönjük a review-t!

@NyesteAmbrusPal @BPelenczei @VitayVanda

2022-11-13 23:35 UTC, NyesteAmbrusPal commented
Sziasztok!

Lehúztam a repot és kipróbáltam és jól működik. 
Azonban amit észrevettem, hogy a unit testek hiányoznak. 
Részletesebb átnézésre holnap lesz lehetőségem.

Üdv,
Pali

2022-11-14 10:29 UTC, szkLaszlo requested changes
Nekem hiányzik a map generátor vagy valami amivel megvalósul az internal wall is. Mert ok, hogy hard-code olva van a txtbe, de tudni kéne létrehozni is térképet, akár tetszőleges méretűt és nem csak betölteni.

2022-11-14 20:42 UTC, farkas-peter commented
> Nekem hiányzik a map generátor vagy valami amivel megvalósul az internal wall is. Mert ok, hogy hard-code olva van a txtbe, de tudni kéne létrehozni is térképet, akár tetszőleges méretűt és nem csak betölteni.

Köszi az észrevételt! Javítottuk.

2022-11-15 08:18 UTC, farkas-peter commented
> Sziasztok!
> 
> Lehúztam a repot és kipróbáltam és jól működik. Azonban amit észrevettem, hogy a unit testek hiányoznak. Részletesebb átnézésre holnap lesz lehetőségem.
> 
> Üdv, Pali

Kedves @NyesteAmbrusPal !

Elkészültünk a unit test résszel is. 

Üdvözlettel:
A Namco csapata

2022-11-15 08:36 UTC, szkLaszlo approved these changes
Köszönöm

2022-11-15 08:40 UTC, NyesteAmbrusPal approved these changes
Köszi! Szerintem így már szuper

2022-11-15 18:55 UTC, BPelenczei requested changes
@farkas-peter @Kurtiadam @Buxi527bme 

Sziasztok!

Tudom, kicsit későn jelentkezem, elnézést kérek. Viszont:
A PR mielőbbi merge-ölését remélve, átnéztem a kódot, észrevételeim a következők:

- a SOLID elveknek teljes mértékben megfelel, struktúrájában rendezett
- CleanCode szempontból van 1-2 kommentem, azok közül nem feltétlenül az összes javítandó, de legalább átgondolandó
- docstringek, typehintek a helyükön, az egyéb kommenteket még feleslegesnek is érzem néhol a kód érthetőségére hivatkozva
- a funkciók az elvárásoknak megfelelően működnek
- elégséges mennyiségűek és minőségűek a testek, lefutnak hiba nélkül
- tetszik, hogy szervezettségében egyéni megoldást alkalmaztatok
- tetszik, hogy figyeltetek a függvények accessibility-jére, kívülről (habár Pythonban hivatalosan public-private nem létezik) csak az látszik, amelyik kell is (ezt esetleg ki lehetne egészíteni a belső változókkal, ha vannak olyanok, amelyekre máshonnan nem feltétlen szükséges biztosítani az elérést)

Összességében teljes, egész kódot adtatok be, ezért gratulálok!

Továbbá legyetek szívesek átnézni az általam kommentezett részeket is, ahol szükséges (néhol inkább: ahogy Ti szükségét érzitek), ott hajtsátok végre a javítást és @tag-eljetek be, amint kész van.

Köszi szépen!


Üdv,
Bálint

2022-11-15 18:55 UTC, BPelenczei commented on Namco/map.py
> +            self.map[row, area_start:(area_start+area_length)] = self.restricted_slot
Tetszik a restricted area-k ((falak)) randomizálása! Esetleg plusz feature-ként elférne, hogy mondjuk argumentumban átadott (kívülről, előre definiált) koordinátá(k)ra is tegyen markert, de ezt rátok bízom természetesen, mivel nem része a feladatnak.

2022-11-15 18:55 UTC, BPelenczei commented on Namco/game_runner.py
> +        dot, wall = self.world.check_interaction(self.agent.position)
Szerintem a dot, wall változó nevekből nem feltétlen derül ki, hogy ezek mit is jelentenek.

2022-11-15 18:55 UTC, BPelenczei commented on Namco/game_runner.py
> +        # Increasing the step number
Információt nem hordozó komment, szerintem törölhető is lehet, de rátok bízom.
```suggestion

```

2022-11-15 18:55 UTC, BPelenczei commented on Namco/game_runner.py
> +        # Terminating the game or increasing the score according to the situation
Ez a komment meg elkerülhető lenne ha a dot, wall változónevekből kiderülne hogy azoknak a termination-höz van közük.
```suggestion

```

2022-11-15 18:55 UTC, BPelenczei commented on Namco/game_runner.py
> +        # Updating the map and visualizing the current state
Szintén mehet, de szerintem ezek egyéni preferenciák, gondoljátok át.
```suggestion

```

2022-11-18 15:53 UTC, farkas-peter commented on Namco/pac_man.py
> +        if action == 'w':
Köszi a javaslatot, megcsináltuk!

2022-11-18 15:53 UTC, farkas-peter commented on Namco/pac_man.py
> +        self.x = x
Megváltoztattuk

2022-11-18 15:53 UTC, farkas-peter commented on Namco/map.py
> +        self.agent_slot = agent_slot
Ez is kész, köszi az ötletet még egyszer

2022-11-18 15:54 UTC, farkas-peter commented on Namco/map.py
> +            self.map[row, area_start:(area_start+area_length)] = self.restricted_slot
Köszi szépen! Az előre definiált fal generálást meghagytuk egy következő sprint feladatának :D

2022-11-18 15:54 UTC, farkas-peter commented on Namco/game_runner.py
> +        dot, wall = self.world.check_interaction(self.agent.position)
Jogos, megváltoztattuk. Köszi!

2022-11-18 15:55 UTC, farkas-peter commented on Namco/game_runner.py
> +        # Increasing the step number
A kód egységessége miatt ezt inkább meghagynánk

2022-11-18 15:55 UTC, farkas-peter commented on Namco/game_runner.py
> +        # Terminating the game or increasing the score according to the situation
Ezt a kommentet is meghagynánk a kód egységessége miatt

2022-11-18 15:55 UTC, farkas-peter commented on Namco/game_runner.py
> +        # Updating the map and visualizing the current state
Ugyan úgy gondoljuk ennél is, mint az előző kettőnél. Ha nem probléma, mi így hagynánk.

2022-11-18 15:56 UTC, farkas-peter commented
> @farkas-peter @Kurtiadam @Buxi527bme
> 
> Sziasztok!
> 
> Tudom, kicsit későn jelentkezem, elnézést kérek. Viszont: A PR mielőbbi merge-ölését remélve, átnéztem a kódot, észrevételeim a következők:
> 
> * a SOLID elveknek teljes mértékben megfelel, struktúrájában rendezett
> * CleanCode szempontból van 1-2 kommentem, azok közül nem feltétlenül az összes javítandó, de legalább átgondolandó
> * docstringek, typehintek a helyükön, az egyéb kommenteket még feleslegesnek is érzem néhol a kód érthetőségére hivatkozva
> * a funkciók az elvárásoknak megfelelően működnek
> * elégséges mennyiségűek és minőségűek a testek, lefutnak hiba nélkül
> * tetszik, hogy szervezettségében egyéni megoldást alkalmaztatok
> * tetszik, hogy figyeltetek a függvények accessibility-jére, kívülről (habár Pythonban hivatalosan public-private nem létezik) csak az látszik, amelyik kell is (ezt esetleg ki lehetne egészíteni a belső változókkal, ha vannak olyanok, amelyekre máshonnan nem feltétlen szükséges biztosítani az elérést)
> 
> Összességében teljes, egész kódot adtatok be, ezért gratulálok!
> 
> Továbbá legyetek szívesek átnézni az általam kommentezett részeket is, ahol szükséges (néhol inkább: ahogy Ti szükségét érzitek), ott hajtsátok végre a javítást és @tag-eljetek be, amint kész van.
> 
> Köszi szépen!
> 
> Üdv, Bálint

Szia! 

Köszi szépen a részletes review-t. Meg is csináltuk amiket írtál. 

Szép hétvégét @BPelenczei !

Üdvözlettel:
A Namco csapata

2022-11-18 17:20 UTC, BPelenczei approved these changes
@farkas-peter @Kurtiadam @Buxi527bme 

Sziasztok!

Minden általam megjelölt problémát megoldottatok, vagy megmagyaráztatok, így részemről mehet a merge, gratulálok!

Üdv,
Bálint

2022-11-18 17:22 UTC, BPelenczei commented
> @farkas-peter @Kurtiadam @Buxi527bme
> 
> Sziasztok!
> 
> Minden általam megjelölt problémát megoldottatok, vagy megmagyaráztatok, így részemről mehet a merge, gratulálok!
> 
> Üdv, Bálint

U.i.: szereztem nektek egy reviewert kárpótlásul @gujgidani személyében :D viszont még mindig kéne egy, esetleg a SegmentFaultosokkal tudnátok üzletelni (?)

2022-11-18 21:23 UTC, gujgidani requested changes
Sziasztok!

Leszedtem a repótokat és átnéztem a kódotokat.

Az első dolog, ami feltűnt, hogy nem igazán vannak elkülönítve a fájlok. Bőszen elkezdtem vizsgálni a pacman.py nevű fájlt, mire rájöttem, hogy az a korábbi verziója a játéknak. Emiatt mindenképp szeretném javasolni, hogy valamilyen mappastruktúrával vagy elnevezéssel különítsétek el az egymáshoz tartozó fájlokat.

Ettől függetlenül a játék működik, a szükséges funkciók és tesztek megtalálhatóak benne. Néhány módosítási javaslatot jelöltem a kódban. Kérlek, fontoljátok meg ezek figyelembe vételét. Ha végeztetek, tag-eljetek bátran. 😄

2022-11-18 21:23 UTC, gujgidani commented on Namco/game_runner.py
> +    def __init__(self, agent: PacMan, world: Map, visualizer: Visualizer, max_step_num: int = 100):
Az elnevezések itt számomra kissé inkonzisztensek (agent, world).

2022-11-18 21:23 UTC, gujgidani commented on Namco/game_runner.py
> +            self.score += 1
Ezt szerintem ki lehetne szervezni egy külön osztályba, később, a check_interaction függvény definiálásánál részletezem, hogy hogy gondolom.

2022-11-18 21:23 UTC, gujgidani commented on Namco/game_runner.py
> +            done = True
Lásd előző komment.

2022-11-18 21:23 UTC, gujgidani commented on Namco/map.py
> +    def check_interaction(self, agent_pos: [int, int]) -> [bool, bool]:
A Map osztály elég sok mindenért felelős, ami szerintem sérti a SOLID alapelvek közül a "Single responsibility"-t. Emiatt javasolnám ennek kiszervezését 2 külön osztályba: az egyikben azt ellenőrizné, hogy a PacMan és a dot között van-e interakció, majd növelné a score-t, a másikban pedig a PacMan és a restricted area-k közti interakciót vizsgálná és terminálná a játékot.

2022-11-18 21:23 UTC, gujgidani commented on Namco/pac_man.py
> +    def process_action(self, action: str):
A korábbi kommentemhez hasonlóan, a "Single responsibility principle"-t szem előtt tartva ezt is kiszervezném egy külön osztályba.

2022-11-19 15:55 UTC, farkas-peter commented on Namco/game_runner.py
> +    def __init__(self, agent: PacMan, world: Map, visualizer: Visualizer, max_step_num: int = 100):
Megváltoztattam a world kifejezést env-re. A map sajnos pythonban egy beépített parancs, így az az elnevezés nem lenne célszerű. Azért használjuk ezeket az elnevezéseket, mert szeretnénk Pacman-függetlenné tenni a programot.

2022-11-19 15:58 UTC, farkas-peter commented on Namco/pac_man.py
> +    def process_action(self, action: str):
Szerintem teljesül az Single responsibility, mert ez az osztály csak az agent-tel kapcsolatos dolgokért felelős. Utána pedig az egyes függvények (kisebb modulok) szintén csak 1-1 feladatot valósítanak meg. Én úgy gondolom, hogy túl darabolt lenne a kód, ha ezeket is szétszednénk és akkor olyan osztályok lennének, amelyek 1-1 függvényt tartalmaznának csak.

2022-11-19 15:59 UTC, farkas-peter commented on Namco/map.py
> +    def check_interaction(self, agent_pos: [int, int]) -> [bool, bool]:
Köszi, jogos észrevétel. Azonban mi úgy gondoltuk/gondoljuk, hogy a Map osztály csak a pályával (más néven környezettel) kapcsolatos teendőkért felelős, így ha számodra nem túl zavaró, mi ezt nem szednénk szét. Arra figyeltünk, hogy az egyes funkciók csak 1-1 feladatot lássanak el.

2022-11-19 16:03 UTC, farkas-peter commented on Namco/game_runner.py
> +            self.score += 1
Ha esetleg lehetséges, mi ezt nem szerveznénk át, mert ez a játékszabályok részét képezi, amit mi a GameRunner osztállyal szerettünk volna megvalósítani.

2022-11-19 16:04 UTC, farkas-peter commented on Namco/game_runner.py
> +            done = True
Hasonlóan gondoljuk, mint amit írtam az előző kommentre adott válaszban.

2022-11-19 16:15 UTC, farkas-peter commented
> Sziasztok!
> 
> Leszedtem a repótokat és átnéztem a kódotokat.
> 
> Az első dolog, ami feltűnt, hogy nem igazán vannak elkülönítve a fájlok. Bőszen elkezdtem vizsgálni a pacman.py nevű fájlt, mire rájöttem, hogy az a korábbi verziója a játéknak. Emiatt mindenképp szeretném javasolni, hogy valamilyen mappastruktúrával vagy elnevezéssel különítsétek el az egymáshoz tartozó fájlokat.
> 
> Ettől függetlenül a játék működik, a szükséges funkciók és tesztek megtalálhatóak benne. Néhány módosítási javaslatot jelöltem a kódban. Kérlek, fontoljátok meg ezek figyelembe vételét. Ha végeztetek, tag-eljetek bátran. 😄

Szia!

Köszi a review-t. Válaszoltam az összes kommentedre :) 

Üdvözlettel:
A Namco csapata

2022-11-19 16:52 UTC, gujgidani commented
> > Sziasztok!
> > Leszedtem a repótokat és átnéztem a kódotokat.
> > Az első dolog, ami feltűnt, hogy nem igazán vannak elkülönítve a fájlok. Bőszen elkezdtem vizsgálni a pacman.py nevű fájlt, mire rájöttem, hogy az a korábbi verziója a játéknak. Emiatt mindenképp szeretném javasolni, hogy valamilyen mappastruktúrával vagy elnevezéssel különítsétek el az egymáshoz tartozó fájlokat.
> > Ettől függetlenül a játék működik, a szükséges funkciók és tesztek megtalálhatóak benne. Néhány módosítási javaslatot jelöltem a kódban. Kérlek, fontoljátok meg ezek figyelembe vételét. Ha végeztetek, tag-eljetek bátran. 😄
> 
> Szia!
> 
> Köszi a review-t. Válaszoltam az összes kommentedre :)
> 
> Üdvözlettel: A Namco csapata

Szia!

Köszi a javításokat és magyarázatokat. Resolve-oltam mindent, amire úgy gondolom, hogy megoldásra/megmagyarázásra került. Egyedül 1 javaslatomat hagytam benn: A check interaction-t én változatlanul kiszervezném egy külön osztályba, mivel a Map többi függvénye a vizualizációra irányul, ez pedig inkább a játékmenetre. Ha ez javításra kerül, onnantól részemről mehet a merge. 😉 

@farkas-peter @Kurtiadam @Buxi527bme

2022-11-19 18:05 UTC, farkas-peter commented
> > > Sziasztok!
> > > Leszedtem a repótokat és átnéztem a kódotokat.
> > > Az első dolog, ami feltűnt, hogy nem igazán vannak elkülönítve a fájlok. Bőszen elkezdtem vizsgálni a pacman.py nevű fájlt, mire rájöttem, hogy az a korábbi verziója a játéknak. Emiatt mindenképp szeretném javasolni, hogy valamilyen mappastruktúrával vagy elnevezéssel különítsétek el az egymáshoz tartozó fájlokat.
> > > Ettől függetlenül a játék működik, a szükséges funkciók és tesztek megtalálhatóak benne. Néhány módosítási javaslatot jelöltem a kódban. Kérlek, fontoljátok meg ezek figyelembe vételét. Ha végeztetek, tag-eljetek bátran. 😄
> > 
> > 
> > Szia!
> > Köszi a review-t. Válaszoltam az összes kommentedre :)
> > Üdvözlettel: A Namco csapata
> 
> Szia!
> 
> Köszi a javításokat és magyarázatokat. Resolve-oltam mindent, amire úgy gondolom, hogy megoldásra/megmagyarázásra került. Egyedül 1 javaslatomat hagytam benn: A check interaction-t én változatlanul kiszervezném egy külön osztályba, mivel a Map többi függvénye a vizualizációra irányul, ez pedig inkább a játékmenetre. Ha ez javításra kerül, onnantól részemről mehet a merge. 😉
> 
> @farkas-peter @Kurtiadam @Buxi527bme

Azt eredetileg mi is külön gondoltuk, ezért volt is neki egy külön osztály 1 db check_interaction függvénnyel, azonban a konzultáció során megmutattuk a kódunkat az előadónak, aki tartotta a SOLID-os órákat és ő javasolta, hogy azt az osztályt szüntessük meg és tegyük a Map osztályba a függvényt.

2022-11-19 18:08 UTC, gujgidani commented
> > > > Sziasztok!
> > > > Leszedtem a repótokat és átnéztem a kódotokat.
> > > > Az első dolog, ami feltűnt, hogy nem igazán vannak elkülönítve a fájlok. Bőszen elkezdtem vizsgálni a pacman.py nevű fájlt, mire rájöttem, hogy az a korábbi verziója a játéknak. Emiatt mindenképp szeretném javasolni, hogy valamilyen mappastruktúrával vagy elnevezéssel különítsétek el az egymáshoz tartozó fájlokat.
> > > > Ettől függetlenül a játék működik, a szükséges funkciók és tesztek megtalálhatóak benne. Néhány módosítási javaslatot jelöltem a kódban. Kérlek, fontoljátok meg ezek figyelembe vételét. Ha végeztetek, tag-eljetek bátran. 😄
> > > 
> > > 
> > > Szia!
> > > Köszi a review-t. Válaszoltam az összes kommentedre :)
> > > Üdvözlettel: A Namco csapata
> > 
> > 
> > Szia!
> > Köszi a javításokat és magyarázatokat. Resolve-oltam mindent, amire úgy gondolom, hogy megoldásra/megmagyarázásra került. Egyedül 1 javaslatomat hagytam benn: A check interaction-t én változatlanul kiszervezném egy külön osztályba, mivel a Map többi függvénye a vizualizációra irányul, ez pedig inkább a játékmenetre. Ha ez javításra kerül, onnantól részemről mehet a merge. 😉
> > @farkas-peter @Kurtiadam @Buxi527bme
> 
> Azt eredetileg mi is külön gondoltuk, ezért volt is neki egy külön osztály 1 db check_interaction függvénnyel, azonban a konzultáció során megmutattuk a kódunkat az előadónak, aki tartotta a SOLID-os órákat és ő javasolta, hogy azt az osztályt szüntessük meg és tegyük a Map osztályba a függvényt.

Értem, ebben az esetben bocsi, hogy emiatt nem fogadtam el a dolgot. 😅 Még én is most először foglalkozom SOLID-dal,  úgyhogy legalább most is tanultam valamit. Ebben az esetben akkor nem állok az útjába a merge-nek, megy is az approve. Gratula a kódhoz! 😁

2022-11-19 18:09 UTC, gujgidani approved these changes

2022-11-21 09:40 UTC, merged