2. sprint: AgiliTeam. Implementing Pacman with ghosts, pellets with timing.
bme-kjit/bosch_ASDIIE pull request #30
Opened 2022-11-08 14:16 UTC by NyesteAmbrusPal

Sziasztok!
Ebben a sprintben terveztük át és implementáltuk le a Pacman-t a SOLID elveknek megfelelően!

Várjuk az észrevételeket és javaslatokat.

Előre is köszönjük a review-t!

2022-11-10 10:26 UTC, markbozsoki commented
Hello
Hozzáadnátok kérlek a PR-hoz hogy én is át tudjam nézni?
@markbozsoki

2022-11-11 08:20 UTC, markbozsoki commented
Sziasztok!
@NyesteAmbrusPal @BPelenczei 
Én is a SegmentFault csapathoz tartozom, kérlek vegyetek be a reviwerek közé!
(A bme-kjit fiók nem fog reviewzni)

2022-11-11 09:43 UTC, markbozsoki commented
Sziasztok!

Lehúztam a repotokat és kipróbáltam a programot.

Fut, nem dob hibát.✅

Viszont, nem jelenik meg jól a játéktér.❎
**Nem jelennek meg rendesen a falak és egyszerre több helyen is mozog a PacMan.**

Az irányítás jónak tűnik.✅

Kérlek nézzétek át a programot!
Belenézek én is hogy hol lehet a lehetséges hibaforrás.

2022-11-11 12:11 UTC, markbozsoki requested changes
Átnézve a kódbázis van egy nagyon súlyos hiányosság: **nincsen semmi sem kommentezve**.
**Legyenek kommentek a függvényekhez és az osztályokhoz!**

A másik dolog, hogy nagyon nehezíti a megérést, hogy minden be van hányva a "core" mappa alá. Kerüljenek külön mappába a különböző típusú vagy funkcionalitással bíró modulok.
Például:
- Az interface-ek kerüljenek egy [core/interfaces] nevű mappába
- Az enum-ok kerüljenek egy [core/enums] nevű mappába
- Kerüljenek szeparált mappába a visualizer és visualizable
- Hasonlóan a game_element, ghost, pacman, pellets
- A move, score_counter, defeat_checker
(A lényeg hogy legyen valami átlátható logika a mapparendszerben)

A testeket nem tudtam futtatni, kérlek legyen valamilyen script amivel gyorsan és egyszerűen futtathatók a tesztek. Vagy használjatok valamilyen könyvtárat.

2022-11-11 12:11 UTC, markbozsoki commented on AgiliTEAM/solid_version/run.py
> +        raise NotImplementedError
Ennek itt mi értelme van?

2022-11-11 12:14 UTC, markbozsoki commented
> Sziasztok!
> 
> Lehúztam a repotokat és kipróbáltam a programot.
> 
> Fut, nem dob hibát.✅
> 
> Viszont, nem jelenik meg jól a játéktér.❎ **Nem jelennek meg rendesen a falak és egyszerre több helyen is mozog a PacMan.**
> 
> Az irányítás jónak tűnik.✅
> 
> Kérlek nézzétek át a programot! Belenézek én is hogy hol lehet a lehetséges hibaforrás.

Közben rájöttem hogy amik még ott mozognak azok valószínűleg a szellemek, ugye?

2022-11-12 09:49 UTC, origergelylaszlo reviewed
Alapvetően jónak látom a kódot, néhány clean code-os és javalatot tettem, illetve néhány fájlban van kiszervezhető redundáns kód. A kommentelés, docstring és a mappastruktúra sokat segítene az érthetőségen és az átláthatóságon.

2022-11-12 09:49 UTC, origergelylaszlo commented on AgiliTEAM/solid_version/core/ghosts.py
> +        if map_size is None:
Ez itt felesleges lépésnek tartom, a `None` helyett lehet a `MapSize(10,10)` a `map_size` változó alapértelmezett értéke.

2022-11-12 09:49 UTC, origergelylaszlo commented on AgiliTEAM/solid_version/core/ghosts.py
> +        for _ in range(num_of_pos):
Az `_` index  nem igazán clean code-os, lehetne neki beszédesebb neve pl.: `pos_list_index`

2022-11-12 09:49 UTC, origergelylaszlo commented on AgiliTEAM/solid_version/core/ghosts.py
> +        for idx in range(len(self.pos)):
Első ránézésre az `idx` index név nem segíti a megértést, clean code-osabb ha nem rövidítés lenne pl.: `position_index`

2022-11-12 09:49 UTC, origergelylaszlo commented on AgiliTEAM/solid_version/core/pacman.py
> +        if known_pos is not None:
A `ghosts.py`-hoz hasonlóan itt is érdemes az alapértelmezett értéket beállítani a `None` helyett mindhárom változóra

2022-11-12 09:49 UTC, origergelylaszlo commented on AgiliTEAM/solid_version/core/pellets.py
> +    def generate_pos(self, num_of_pos: int, map_size: MapSize) -> List[Coordinates]:
Redundáns kód, karakterről karakterre  megegyezik a `ghosts.py` 36-45 soraival és funkcionalitásában a `pacman.py` 35-39 soraival át kellene rakni egy másik osztályba, és meghívni.

2022-11-12 09:49 UTC, origergelylaszlo commented on AgiliTEAM/solid_version/core/pacman.py
> +    def generate_pos(self, num_of_pos: int, map_size: MapSize) -> List[Coordinates]:
Redundáns kód, funkcionalitásában megegyezik a `ghosts.py` 36-45 soraival

2022-11-12 14:07 UTC, Amontobix commented on AgiliTEAM/solid_version/run.py
> +    args = arg_parser.parse_args()
Ezt a megoldás nekem se tetszik annyira, ezeket a változókat lehetne egy enumba tárolni és később onnan meghívni mint hogy globálisak legyenek

2022-11-12 14:08 UTC, Amontobix commented on AgiliTEAM/solid_version/run.py
> +    args = arg_parser.parse_args()
Tehát lehetne egy default_values.py vagy valami hasonló modul ahol ezek a default értékek lennének és akkor átláthatóbb szerintem, hogy honnan jönnek

2022-11-12 14:10 UTC, Amontobix commented on AgiliTEAM/solid_version/run.py
> +    args = arg_parser.parse_args()
Valamint az argument parsernak is lehetne egy külön modulja ahol ki lehet szedni egy GetConfig függvényel az összes paramétert de ez nem annyira fontos

2022-11-12 14:16 UTC, Amontobix commented on AgiliTEAM/solid_version/run.py
> +                    step_confidence=args.ghost_step_confidence)
Igen, így a hard coded paramokat inicializálja a játék a helyes így lenne: 

Pl.: a height-ra: egy GetConfiguredHeight(self): metodust csinálni szerintem
configured_mapheight = self.args.map_height
return configured_mapheight

és ez az összes többi argumentumra is hasonló lehetne, ha van még rá időtök, ha nincs akkor elég csak az amit a @markbozsoki  írt

2022-11-12 14:23 UTC, Amontobix commented
Sziasztok!

Nekem is hasonlóak a meglátásaim, mint a többieknek, a kommentelést, docstringeket és a typehintet én is hiányolom. Valamint az Argument Parser modul használata, nem tetszik számomra annyira. Kérlek azt javítsátok, hogy a Map méret tényleg az argument parserból érkező értékeket fogadja, valamint a többi ilyen konfigurálható beállítás is. 
A tesztek inkább regressziós és integrációs jellegűnek tűnnek számomra, de szerintem ez nem baj. 

De látszik hogy sokat foglalkoztatok vele, és igényes, szép munkának tartom, a hiányosságok ellenére is. 

Üdv.: Pali

2022-11-12 14:25 UTC, Amontobix requested changes
Sziasztok!

Nekem is hasonlóak a meglátásaim, mint a többieknek, a kommentelést, docstringeket és a typehintet én is hiányolom. Valamint az Argument Parser modul használata, nem tetszik számomra annyira. Kérlek azt javítsátok, hogy a Map méret tényleg az argument parserból érkező értékeket fogadja, valamint a többi ilyen konfigurálható beállítás is.
A tesztek inkább regressziós és integrációs jellegűnek tűnnek számomra, de szerintem ez nem baj.

De látszik hogy sokat foglalkoztatok vele, és igényes, szép munkának tartom, a hiányosságok ellenére is.

Üdv.: Pali

2022-11-13 17:11 UTC, BPelenczei commented on AgiliTEAM/solid_version/run.py
> +from bosch_ASDIIE.AgiliTEAM.solid_version.core.defeat_checker import DefeatChecker
@markbozsoki 
Javítva, az összes file-ban. Localban workspace root-tal a pycharm így szereti, remote-on futtatva úgy a helyes ahogy írta is, köszi!

2022-11-13 17:14 UTC, BPelenczei commented on AgiliTEAM/solid_version/run.py
> +    args = arg_parser.parse_args()
@markbozsoki @Amontobix 

Így belegondolva tényleg nem egy szép megoldás, azóta orvosolva lett:

- a default value-k egy .yaml fájl által módosíthatók
- ha a run.py hoz hozzáadtok argumentumokat, az argparser felülírja a yaml default configját
- kiszerveztem mind az argparsert mind pedig a config loadert külön classba

2022-11-13 17:16 UTC, BPelenczei commented on AgiliTEAM/solid_version/run.py
> +                    step_confidence=args.ghost_step_confidence)
@markbozsoki @Amontobix 
Jogos, szimpla elírás volt ebben az esetben, de a config modification-nél ez is javítva lett.

2022-11-13 17:41 UTC, markbozsoki commented on AgiliTEAM/solid_version/core/ghosts.py
> +        for _ in range(num_of_pos):
@origergelylaszlo 
A "_" ebben az esetbe nem változó.
Ez a kódrészlet azt jelenti, hogy példányosított változó nélkül fut végig a for ciklus.
Nincs gond ezzel a sorral.
(Olyasmi mint a C#-ban a foreach.)

2022-11-13 17:45 UTC, BPelenczei commented on AgiliTEAM/solid_version/gui/console_canvas.py
> +    }
@markbozsoki 
javítva egy hibrid megoldással, úgy mint a keyevent-eknél... ha esetleg itt tudsz valami jobbat (mert ez nekem kicsit fura) akkor szívesen veszem.

2022-11-13 17:47 UTC, BPelenczei commented on AgiliTEAM/solid_version/test/pacman_test.py
> +
@markbozsoki 
a test-ek is át lettek strukturálva, illetve lib felhasználása is megtörtént, de még 1-2 additional unittest implementálása folyamatban van, ma estig megleszünk azokkal is, ezért még türelmedet kérném

2022-11-13 17:47 UTC, BPelenczei commented on AgiliTEAM/solid_version/test/pacman_test.py
> +        "Error during step, value mismatch"
@markbozsoki 
javítva

2022-11-13 17:48 UTC, BPelenczei commented on AgiliTEAM/solid_version/test/pacman_test.py
> +        "The game should have ended due too the number of ghost which makes impossible to escape them."
@markbozsoki 
nem releváns a továbbiakban.

2022-11-13 17:49 UTC, BPelenczei commented on AgiliTEAM/solid_version/run.py
> +        raise NotImplementedError
@markbozsoki 
jövőbeli fejleszthetőség lehetősége, de kivettem, így javítva van úgymond

2022-11-13 17:50 UTC, BPelenczei commented on AgiliTEAM/solid_version/core/ghosts.py
> +        if map_size is None:
@origergelylaszlo 
Igazad van, redundáns, javítottuk.

2022-11-13 17:52 UTC, BPelenczei commented on AgiliTEAM/solid_version/core/ghosts.py
> +        for _ in range(num_of_pos):
@origergelylaszlo 
Kicseréltem, de szerintem ez egy tipikus 'throwaway variable', tehát ha nem kell az értéke, feleslegesen nem foglalja a memóriát.

2022-11-13 17:53 UTC, BPelenczei commented on AgiliTEAM/solid_version/core/ghosts.py
> +        for idx in range(len(self.pos)):
@origergelylaszlo 
Nagyjából egyetértek, bár szerintem az eredeti is adja magát, mindenesetre cserélve lett.

2022-11-13 17:55 UTC, BPelenczei commented on AgiliTEAM/solid_version/core/pacman.py
> +        if known_pos is not None:
@origergelylaszlo 
A fentebbihez hasonlóan javítva lett.
A known_pos egy lista, ami ugyebár mutable type, default value-ként nem jó megadni (mint üres listát), tehát azt hagytam.

2022-11-13 17:56 UTC, BPelenczei commented on AgiliTEAM/solid_version/core/pellets.py
> +    def generate_pos(self, num_of_pos: int, map_size: MapSize) -> List[Coordinates]:
@origergelylaszlo 
Igaz, ki lett szervezve külön class-ba.

2022-11-13 17:56 UTC, BPelenczei commented on AgiliTEAM/solid_version/core/pacman.py
> +    def generate_pos(self, num_of_pos: int, map_size: MapSize) -> List[Coordinates]:
@origergelylaszlo 
Ahogy egyel fentebb írtam, javítva.

2022-11-13 17:57 UTC, markbozsoki commented on AgiliTEAM/solid_version/gui/console_canvas.py
> +    }
@BPelenczei
Ha a hibrid megoldás alatt az enum dictionary-ba való áttöltésére érted (a key_listener.py-ban), akkor van egy ennél jobb megközelítés szerintem.

2022-11-13 18:00 UTC, BPelenczei commented
> Sziasztok!
> 
> Nekem is hasonlóak a meglátásaim, mint a többieknek, a kommentelést, docstringeket és a typehintet én is hiányolom. Valamint az Argument Parser modul használata, nem tetszik számomra annyira. Kérlek azt javítsátok, hogy a Map méret tényleg az argument parserból érkező értékeket fogadja, valamint a többi ilyen konfigurálható beállítás is. A tesztek inkább regressziós és integrációs jellegűnek tűnnek számomra, de szerintem ez nem baj.
> 
> De látszik hogy sokat foglalkoztatok vele, és igényes, szép munkának tartom, a hiányosságok ellenére is.
> 
> Üdv.: Pali

Szia,

A kommentelést, docstringeket, typehinteket feltöltöttem, viszont még nincsenek megtöltve érdemleges információval, ezt ma estig megtesszük.
Az argparser modul-t ahogy a code review egyes részein jeleztem ki lett szervezve, ileltve egy config_loader class is létrejött ami egy .yaml fájl által átláthatóbbá teszi (reméljük) az init param-okat.
A map paraméter csak elírás volt, hogy nem argparserből érkezett, de az is javítva lett természetesen.

A tesztek részéről az tudom mondani, hogy estig még az az elem is készülőben van unit testekkel kiegészülve, hogy mind nektek mind pedig a feladatkiírásnak is megfeleljünk. :)

Köszi szépen a reviewt!


Üdv,
Bálint

2022-11-13 18:05 UTC, BPelenczei commented
> Alapvetően jónak látom a kódot, néhány clean code-os és javalatot tettem, illetve néhány fájlban van kiszervezhető redundáns kód. A kommentelés, docstring és a mappastruktúra sokat segítene az érthetőségen és az átláthatóságon.

@origergelylaszlo 

Szia,

A redundanciákat igyekeztünk megszüntetni, ezt majd (remélem) látni is fogod.
A mappa struktúra át lett alakítva, mostmár talán mindannyiunknak érthetőbb a kód szerveződése/átláthatósága.
Kommenteket én speciál úgy gondolom, hogy csak okkal kell használni, hiszen feleslegesen nem kell azt magyarázni amit a kód maga megtesz, de ezt mindenképpen átgondoljuk még.
A docstringek, typehintek tekintetében már megtettük az első lépést (hozzáadtuk őket üresen, lol 👍 ), viccet félretéve ma később este a kiegészített verzió is megjön elvileg.

Köszi a reviewt Neked is!


Üdv,
Bálint

2022-11-13 18:06 UTC, BPelenczei commented
> > Sziasztok!
> > Lehúztam a repotokat és kipróbáltam a programot.
> > Fut, nem dob hibát.✅
> > Viszont, nem jelenik meg jól a játéktér.❎ **Nem jelennek meg rendesen a falak és egyszerre több helyen is mozog a PacMan.**
> > Az irányítás jónak tűnik.✅
> > Kérlek nézzétek át a programot! Belenézek én is hogy hol lehet a lehetséges hibaforrás.
> 
> Közben rájöttem hogy amik még ott mozognak azok valószínűleg a szellemek, ugye?

@markbozsoki 

Így van, a mozgó x-ek ghostok akarnak lenni :D, mellette egy @ jelenti a pacmant.

2022-11-13 18:10 UTC, BPelenczei commented
> Átnézve a kódbázis van egy nagyon súlyos hiányosság: **nincsen semmi sem kommentezve**. **Legyenek kommentek a függvényekhez és az osztályokhoz!**
> 
> A másik dolog, hogy nagyon nehezíti a megérést, hogy minden be van hányva a "core" mappa alá. Kerüljenek külön mappába a különböző típusú vagy funkcionalitással bíró modulok. Például:
> 
> * Az interface-ek kerüljenek egy [core/interfaces] nevű mappába
> * Az enum-ok kerüljenek egy [core/enums] nevű mappába
> * Kerüljenek szeparált mappába a visualizer és visualizable
> * Hasonlóan a game_element, ghost, pacman, pellets
> * A move, score_counter, defeat_checker
>   (A lényeg hogy legyen valami átlátható logika a mapparendszerben)
> 
> A testeket nem tudtam futtatni, kérlek legyen valamilyen script amivel gyorsan és egyszerűen futtathatók a tesztek. Vagy használjatok valamilyen könyvtárat.

@markbozsoki 

Szia,

Kollégának már leírtam, hogy mit gondolok a pure commentekről:
> Kommenteket én speciál úgy gondolom, hogy csak okkal kell használni, hiszen feleslegesen nem kell azt magyarázni amit a kód maga megtesz, de ezt mindenképpen átgondoljuk még.
Ehhez nagyjából tartanám magam, természetesen a docstringek, typehintek hiányában tökéletesen igazad van, ezek orvosolva lesznek még a mai nap folyamán.
A külön mappákba szervezés megtörtént, köszi a tippet a struktúráért, nagyjából tartottam is magam hozzá.
Test probléma elvileg megoldódott könyvtár használatával, de ahogy kcisit feljebb jeleztem már, a test-ek kibővítése is várható még a mai nap végén.


Köszi szépen a teljeskörű átvizsgálást, tényleg! :)


Üdv,
Bálint

2022-11-13 18:12 UTC, BPelenczei commented
> Sziasztok!
> 
> Lehúztam a repotokat és kipróbáltam a programot.
> 
> Fut, nem dob hibát.✅
> 
> Viszont, nem jelenik meg jól a játéktér.❎ **Nem jelennek meg rendesen a falak és egyszerre több helyen is mozog a PacMan.**
> 
> Az irányítás jónak tűnik.✅
> 
> Kérlek nézzétek át a programot! Belenézek én is hogy hol lehet a lehetséges hibaforrás.

@markbozsoki 

Bocsi, csak visszafele haladtam a feed-ben mint egy rák...
Falak mostmár nem csak elvileg de gyakorlatilag is láthatóak lettek, a több pacman problémáját korábban megválaszoltam én is, de Te is magadnak.

2022-11-13 18:18 UTC, markbozsoki requested changes
A legtöbb dolog orvosolva lett.
Az enum-ok legyenek rendbe téve, az <enum_name>.__members__.values() megoldással.

És továbbra is hiányolom a kommenteket. Legyenek pár szavas kommentek a függvényekhez amiből legalább az kiderül hogy mi a függvény célja.

2022-11-13 18:18 UTC, markbozsoki commented on AgiliTEAM/solid_version/core/key_interaction/key_listener.py
> +                if key in self.KEY_PRESS_TO_KEY_EVENT:
self.KEY_PRESS_TO_KEY_EVENT helyett legyen KeyEvent.__members__.values()
És akkor elhagyható a dictionary

2022-11-13 18:18 UTC, markbozsoki commented on AgiliTEAM/solid_version/core/key_interaction/key_listener.py
> +        key_event = self.KEY_PRESS_TO_KEY_EVENT[self.last_key]
Itt legyen 4 if a KeyEvent enum értékvizsgálatához (NE LEGYENEK ELSE ÁGAK!!!)
Vagy egy for ciklus a KeyEvent.__members__.values()-on futtatva.
DE az enum-okat ne töltsük át listákba ha nem feltétlenül szükséges!

2022-11-13 18:18 UTC, markbozsoki commented on AgiliTEAM/solid_version/gui/console_canvas.py
> +    }
Ha enumot használunk akkor ne töltsük át az értékeket egy másik listbe vagy tárolóba.
Felesleges komplexitást ad a kódba.

2022-11-13 18:18 UTC, markbozsoki commented on AgiliTEAM/solid_version/gui/console_canvas.py
> +            self.map[dot.row][dot.col] = self.OBJECT_MARKERS[obj_type].value
itt is legyen enum használva, mint a keyevent-nél
legyen 4 if a négy enumban tárolt object-hez (NE LEGYENEK ELSE ÁGAK!)

2022-11-13 18:37 UTC, markbozsoki commented
> > Átnézve a kódbázis van egy nagyon súlyos hiányosság: **nincsen semmi sem kommentezve**. **Legyenek kommentek a függvényekhez és az osztályokhoz!**
> > A másik dolog, hogy nagyon nehezíti a megérést, hogy minden be van hányva a "core" mappa alá. Kerüljenek külön mappába a különböző típusú vagy funkcionalitással bíró modulok. Például:
> > 
> > * Az interface-ek kerüljenek egy [core/interfaces] nevű mappába
> > * Az enum-ok kerüljenek egy [core/enums] nevű mappába
> > * Kerüljenek szeparált mappába a visualizer és visualizable
> > * Hasonlóan a game_element, ghost, pacman, pellets
> > * A move, score_counter, defeat_checker
> >   (A lényeg hogy legyen valami átlátható logika a mapparendszerben)
> > 
> > A testeket nem tudtam futtatni, kérlek legyen valamilyen script amivel gyorsan és egyszerűen futtathatók a tesztek. Vagy használjatok valamilyen könyvtárat.
> 
> @markbozsoki
> 
> Szia,
> 
> Kollégának már leírtam, hogy mit gondolok a pure commentekről:
> 
> > Kommenteket én speciál úgy gondolom, hogy csak okkal kell használni, hiszen feleslegesen nem kell azt magyarázni amit a kód maga megtesz, de ezt mindenképpen átgondoljuk még.
> 
> Ehhez nagyjából tartanám magam, természetesen a docstringek, typehintek hiányában tökéletesen igazad van, ezek orvosolva lesznek még a mai nap folyamán. A külön mappákba szervezés megtörtént, köszi a tippet a struktúráért, nagyjából tartottam is magam hozzá. Test probléma elvileg megoldódott könyvtár használatával, de ahogy kcisit feljebb jeleztem már, a test-ek kibővítése is várható még a mai nap végén.
> 
> Köszi szépen a teljeskörű átvizsgálást, tényleg! :)
> 
> Üdv, Bálint

Én most nem fogok elkezdeni vitatkozni a kommentezünk mindent is vs. a kód magyarázza magát dologról.

Lényeg, hogy a kódot átnézve többször is meg kellett vakarjam a fejem, hogy ez a függvény vagy osztály mire való.
Mivel mindenhonnan hiányzik a kommentelés, így nem fogom egyesével minden függvényhez odaírni, hogy itt szeretném a következő kommentet látni mert ezt-azt nem értem.

Nem azt várjuk, hogy írd le még egyszer a kódot a kommentbe! Hanem, hogy az adott függvény vagy osztály programban való céljáról/elhelyezkedéséről írjatok valami információt.

Minimális mennyiségű magyarázó jellegű kommentezés hiányában nem fogjuk tudni tovább engedni a PR-t.

Üdv,
Márk

2022-11-13 18:55 UTC, markbozsoki commented
Teszteket megnéztem.
Futnak és OK-osak is (pun intended).✅

2022-11-13 20:27 UTC, BPelenczei commented
> > > Átnézve a kódbázis van egy nagyon súlyos hiányosság: **nincsen semmi sem kommentezve**. **Legyenek kommentek a függvényekhez és az osztályokhoz!**
> > > A másik dolog, hogy nagyon nehezíti a megérést, hogy minden be van hányva a "core" mappa alá. Kerüljenek külön mappába a különböző típusú vagy funkcionalitással bíró modulok. Például:
> > > 
> > > * Az interface-ek kerüljenek egy [core/interfaces] nevű mappába
> > > * Az enum-ok kerüljenek egy [core/enums] nevű mappába
> > > * Kerüljenek szeparált mappába a visualizer és visualizable
> > > * Hasonlóan a game_element, ghost, pacman, pellets
> > > * A move, score_counter, defeat_checker
> > >   (A lényeg hogy legyen valami átlátható logika a mapparendszerben)
> > > 
> > > A testeket nem tudtam futtatni, kérlek legyen valamilyen script amivel gyorsan és egyszerűen futtathatók a tesztek. Vagy használjatok valamilyen könyvtárat.
> > 
> > 
> > @markbozsoki
> > Szia,
> > Kollégának már leírtam, hogy mit gondolok a pure commentekről:
> > > Kommenteket én speciál úgy gondolom, hogy csak okkal kell használni, hiszen feleslegesen nem kell azt magyarázni amit a kód maga megtesz, de ezt mindenképpen átgondoljuk még.
> > 
> > 
> > Ehhez nagyjából tartanám magam, természetesen a docstringek, typehintek hiányában tökéletesen igazad van, ezek orvosolva lesznek még a mai nap folyamán. A külön mappákba szervezés megtörtént, köszi a tippet a struktúráért, nagyjából tartottam is magam hozzá. Test probléma elvileg megoldódott könyvtár használatával, de ahogy kcisit feljebb jeleztem már, a test-ek kibővítése is várható még a mai nap végén.
> > Köszi szépen a teljeskörű átvizsgálást, tényleg! :)
> > Üdv, Bálint
> 
> Én most nem fogok elkezdeni vitatkozni a kommentezünk mindent is vs. a kód magyarázza magát dologról.
> 
> Lényeg, hogy a kódot átnézve többször is meg kellett vakarjam a fejem, hogy ez a függvény vagy osztály mire való. Mivel mindenhonnan hiányzik a kommentelés, így nem fogom egyesével minden függvényhez odaírni, hogy itt szeretném a következő kommentet látni mert ezt-azt nem értem.
> 
> Nem azt várjuk, hogy írd le még egyszer a kódot a kommentbe! Hanem, hogy az adott függvény vagy osztály programban való céljáról/elhelyezkedéséről írjatok valami információt.
> 
> Minimális mennyiségű magyarázó jellegű kommentezés hiányában nem fogjuk tudni tovább engedni a PR-t.
> 
> Üdv, Márk

@markbozsoki 
Akkor valószínűleg félreértettük egymást, mivel amit írsz azzal teljes mértékben egyetértek.
Amit te hiányolsz azok ha jól értem a docstringek, azokat természetesen pótolni fogjuk (párszor már írtam is, ezzel nem én foglalkozom, így nem tudok pontosabbat mondani, de nagyjából ma estig fel fogjuk azokat is commitolni).
Amiről szól a véleményem, az a kód-közi commentek sokasága, amit igyekszek elkerülni, de ha úgy érzem (vagy érzitek/érezzük/érzik) hogy valahol igényel egy kis plusz magyarázat a kód, akkor ott is alkalmazom.


Üdv,
Bálint

2022-11-13 22:16 UTC, BPelenczei commented on AgiliTEAM/solid_version/core/key_interaction/key_listener.py
> +                if key in self.KEY_PRESS_TO_KEY_EVENT:
@markbozsoki 
Köszi a segítséget, kijavítottam, légyszíves rá tudnál nézni, hogy így megfelel-e?

2022-11-13 22:17 UTC, BPelenczei commented on AgiliTEAM/solid_version/core/key_interaction/key_listener.py
> +        key_event = self.KEY_PRESS_TO_KEY_EVENT[self.last_key]
A fentivel együtt javítva.

2022-11-13 22:17 UTC, BPelenczei commented on AgiliTEAM/solid_version/gui/console_canvas.py
> +    }
Szintén a fentivel együtt javítva.

2022-11-13 22:17 UTC, BPelenczei commented on AgiliTEAM/solid_version/gui/console_canvas.py
> +            self.map[dot.row][dot.col] = self.OBJECT_MARKERS[obj_type].value
És ez is javítva a többivel együtt

2022-11-13 22:20 UTC, BPelenczei commented
> A legtöbb dolog orvosolva lett. Az enum-ok legyenek rendbe téve, az <enum_name>.**members**.values() megoldással.
> 
> És továbbra is hiányolom a kommenteket. Legyenek pár szavas kommentek a függvényekhez amiből legalább az kiderül hogy mi a függvény célja.

@markbozsoki 

Szia,
Köszi szépen a gyors hozzászólást, átnézést!
Az enumos dolgok elméletben javítva, a kommentek, tesztek kiegészítése még várat magára.
Türelmed és segítséged előre is köszönjük.


Üdv,
Bálint

2022-11-14 08:24 UTC, origergelylaszlo commented on AgiliTEAM/solid_version/core/ghosts.py
> +        for _ in range(num_of_pos):
Ezt nem ismertem pythonban, akkor nem szóltam, maradhat az eredeti változat.

2022-11-14 09:17 UTC, BPelenczei commented
@markbozsoki @Amontobix @origergelylaszlo @leonsuszter 

Sziasztok!

Elkészültünk a javított változattal, igyekeztünk minden igényt kielégíteni.
Ha lesz rá időtök, légyszi nézzétek át, hogy adresszáltunk-e mindent.


Üdv,
Bálint

2022-11-14 10:11 UTC, szkLaszlo approved these changes
Jó lesz :) a számomra fontos dolgok rendben, a többiek meg majd adják hozzá a tartalmat 👍

2022-11-14 17:27 UTC, markbozsoki approved these changes
Szerintem minden megvan amit kértünk.
Nagyon ügyes munka. :)

2022-11-14 17:31 UTC, BPelenczei commented
> Szerintem minden megvan amit kértünk.
> 
> Nagyon ügyes munka. :)

Köszi szépen!
De azért van még hova... 😃

2022-11-14 17:44 UTC, origergelylaszlo approved these changes

2022-11-14 17:46 UTC, Amontobix approved these changes

2022-11-14 23:30 UTC, gujgidani approved these changes
Sziasztok!

A közeli merge határidő miatt, beugró reviewerként átnéztem a kódot.

Amiket vizsgáltam:
- A szükséges funkciók megléte.
- A kód struktúrája, a SOLID alapelveknek való megfelelés.
- A tesztek megléte és működése.
- A korábbi sprint szempontjai (főleg Clean Code)

Az előttem szóló reviewerek rendkívül alapos munkát végeztek, minden részletre kitértek. Saját áttekintésem szempontjából: A kód fut, a szükséges funkciók megvannak benne. Struktúráját tekintve jól áttekinthető és érthető, logikailag is megfelelő. A kommentek is segítik a megértést. A tesztek pedig megvannak és működnek is.

Ezen szempontok figyelembe vételével úgy érzem, hogy én már érdemben nem tudok hozzátenni a kódotokhoz. Szép munka, gratula hozzá! 😁

2022-11-14 23:45 UTC, merged