SegmentFault: 2. sprint PR
bme-kjit/bosch_ASDIIE pull request #32
Opened 2022-11-08 14:58 UTC by markbozsoki

@szkLaszlo 
Elkészültünk a fejlesztéssel, implementált funkciók:
- walls on the border of the map
- GameOver feature
- if the player hits any wall dies

2022-11-08 20:19 UTC, istvan-knab requested changes
Alapvetően tetszik a kód , pár javasolt változtatás ami valószínűleg elkerülte a figyelmeteket . Tetszik a struktúra , sokat dobott rajta a pár extra , ami nem volt megadva a feladat kiírásában. Részemről ennyi észrevétel , szép munka.

2022-11-08 20:29 UTC, istvan-knab requested changes
Alapvetően tetszik a kód , pár javasolt változtatás ami valószínűleg elkerülte a figyelmeteket . Tetszik a struktúra , sokat dobott rajta a pár extra , ami nem volt megadva a feladat kiírásában. Részemről ennyi észrevétel , szép munka.

2022-11-08 20:29 UTC, istvan-knab commented on SegmentFault/source/dynamic_elements/moveables/Player.py
> +        #TODO: check for cherry
Ide jönnének a feljebb említett üres kódok?

2022-11-08 20:29 UTC, istvan-knab commented on solid_version/gui/console_canvas.py
> +
Függvények rövid leírását hiányolom ( docstring)

2022-11-08 20:29 UTC, istvan-knab commented on solid_version/run.py
> +    snake = Snake(map_size=MapSize(HEIGHT, WIDTH))
Konstruktor és osztály neve pacman legyen , gondolom elsiklottatok felette .

2022-11-08 20:29 UTC, istvan-knab commented on solid_version/core/snake.py
> +    def draw(self, canvas: Canvas):
visszatérési érték , docstring sokat segítene

2022-11-08 20:29 UTC, istvan-knab commented on solid_version/core/snake.py
> +class Snake(GameElement, Visualizable):
Osztály neve 😃

2022-11-08 20:29 UTC, istvan-knab commented on solid_version/core/snake.py
> +            self.body_parts = deque([
Szerintem nem indokolt a deque használata , 1 lesz a kiterjedése a játékosnak.

2022-11-08 20:29 UTC, istvan-knab commented on solid_version/core/screen.py
> +    def __getattr__(self, attr):
return parameter ->

2022-11-08 20:34 UTC, istvan-knab requested changes
Ez lemaradt

2022-11-08 20:34 UTC, istvan-knab commented on SegmentFault/source/dynamic_elements/emergers/Door.py
> +/ PROJECT_NAME : PacMan
Ez lemaradt , ez lenne amire feljebb említettként hivatkozok , csak comment van benne , semmi sincs implementálva , gondolom ez majd később lesz

2022-11-08 20:34 UTC, istvan-knab commented on SegmentFault/source/dynamic_elements/emergers/Door.py
> +**********************************************************************
Itt is

2022-11-08 20:35 UTC, istvan-knab commented
Ezen kívül tényleg nagyon 🔥 🚀  , gratula

2022-11-08 21:18 UTC, markbozsoki commented on solid_version/run.py
> +    snake = Snake(map_size=MapSize(HEIGHT, WIDTH))
Ezt a kódot nem mi írtuk.
Ez a megadott SOLID példa kód.

2022-11-08 21:19 UTC, markbozsoki commented on solid_version/core/snake.py
> +    def draw(self, canvas: Canvas):
Ezt sem mi írtuk.
Példakód

2022-11-08 21:19 UTC, markbozsoki commented on solid_version/core/snake.py
> +class Snake(GameElement, Visualizable):
Nem mi írtuk
Példakód

2022-11-08 21:19 UTC, markbozsoki commented on solid_version/core/snake.py
> +            self.body_parts = deque([
Példakód

2022-11-08 21:20 UTC, markbozsoki commented on solid_version/core/screen.py
> +    def __getattr__(self, attr):
Példakód
Nem mi írtuk

2022-11-08 21:23 UTC, markbozsoki commented on SegmentFault/source/dynamic_elements/emergers/Door.py
> +/ PROJECT_NAME : PacMan
Majd csak a szellemekkel együtt lesz implementálva

2022-11-08 21:24 UTC, istvan-knab commented on solid_version/core/screen.py
> +    def __getattr__(self, attr):
elnézést , elnéztem a mappát, bocsi

2022-11-09 07:21 UTC, markbozsoki commented on solid_version/core/screen.py
> +    def __getattr__(self, attr):
A példakódos kommenteknél egy Resolve-ot tudnál nyomni?

2022-11-09 13:50 UTC, istvan-knab approved these changes
Akkor viszont részemről rendben van 🔥

2022-11-12 11:28 UTC, markbozsoki commented
@TothAron @TerrorTegla 
Sziasztok!
Várjuk a reviewkat!
( @TerrorTegla  feltételezem, hogy te is a review csapathoz tartozol)

2022-11-14 09:56 UTC, szkLaszlo requested changes
Összességében jó :) Néhány kommentet leszámítva. meg nekem a docstring formázással van kis bajom de az már csak egyéni preference :) (pl hogy a """ újsor szöveg újsor """ a függvények docstringjénél) egy ctrl+alt+L és ctrl+alt+O mehet a fájlokon pycharmban, hogy berendezzen mindent. 
Írjatok ha megvannak a kommentek.

2022-11-14 09:56 UTC, szkLaszlo commented on SegmentFault/data/assets/Simple_title.txt
> +
jó kis wordart :D

2022-11-14 09:56 UTC, szkLaszlo commented on SegmentFault/source/dynamic_elements/moveables/Ghost.py
> +
Ez így működik? nem dob errort? sztem hiányzik egy pass vagy valami. A többinél ugyanígy

2022-11-14 09:56 UTC, szkLaszlo commented on SegmentFault/source/dynamic_elements/moveables/Moveable.py
> +class Movable():
Kicsit furcsa hogy nincs init függvény de ha működik akkor jó 👍

2022-11-14 09:56 UTC, szkLaszlo commented on SegmentFault/source/dynamic_elements/moveables/Moveable.py
> +        for coord in mapdata.obstacles.walls:
```return next_position in mapdata.obstacles.walls```
Akkor nem kell a for :)

2022-11-14 09:56 UTC, szkLaszlo commented on SegmentFault/source/dynamic_elements/moveables/Player.py
> +class Player(Moveable.Movable):
miért Moveable.Movable? amúgy sztem az csak Movable: 
![image](https://user-images.githubusercontent.com/46420090/201627917-b97446e4-8d1b-444d-9ab6-8128cc68449b.png)

2022-11-14 09:56 UTC, szkLaszlo commented on SegmentFault/source/dynamic_elements/moveables/Player.py
> +        # change the direction, if turning is available
nagyon szuper, de sok a super hívás :) a selfnek is van olyan, hogy next_position, ha jó az öröklés. de ugye az elég furcsa illetve a movablenek sincs construktora. Érdemes ezt átnézni

2022-11-14 09:56 UTC, szkLaszlo commented on SegmentFault/source/map/MapDataReader.py
> +        # get collectables start pozition
mindenhol pls

2022-11-14 09:56 UTC, szkLaszlo commented on SegmentFault/source/ui/ColorfullVisualizer.py
> +class ColorfullVisualizer:
Colorful*

2022-11-14 18:14 UTC, markbozsoki commented on SegmentFault/source/dynamic_elements/moveables/Moveable.py
> +        for coord in mapdata.obstacles.walls:
Javítva

2022-11-14 18:15 UTC, markbozsoki commented on SegmentFault/source/map/MapDataReader.py
> +        # get obsticles start pozition
Javítva

2022-11-14 18:15 UTC, markbozsoki commented on SegmentFault/source/ui/ColorfullVisualizer.py
> +class ColorfullVisualizer:
Javítva
A fájlnév is

2022-11-14 18:18 UTC, origergelylaszlo commented
@markbozsoki 
Ok, így lesz :)

> @origergelylaszlo Geri legközelebb ha valamit javítasz vagy mókolsz nagyon szépen megkérlek azt a kommentekben is írd oda hogy javítottál valamit! Köszi

2022-11-14 18:36 UTC, markbozsoki commented on SegmentFault/source/dynamic_elements/moveables/Player.py
> +class Player(Moveable.Movable):
Javítva.
A mappa is át lett nevezve és a testeknél is kijavítottam.

2022-11-14 18:36 UTC, markbozsoki commented on SegmentFault/source/dynamic_elements/moveables/Ghost.py
> +
Kipróbáltam Mobában és nekem nem dobott hibát, mondjuk ez a modul még nincs bekötve a játékmenetbe.
Javítottam

2022-11-14 21:03 UTC, markbozsoki commented on SegmentFault/source/dynamic_elements/moveables/Player.py
> +        # change the direction, if turning is available
Javítva

2022-11-14 21:04 UTC, markbozsoki commented on SegmentFault/source/dynamic_elements/moveables/Moveable.py
> +class Movable():
Javítva a Player.py modulhoz fűzött hozzászólásnak megfelelően

2022-11-14 21:06 UTC, markbozsoki commented
@szkLaszlo
Javítottuk a hibákat.

2022-11-15 08:34 UTC, szkLaszlo approved these changes

2022-11-15 21:21 UTC, TothAron approved these changes

2022-11-15 22:25 UTC, markbozsoki commented on SegmentFault/source/dynamic_elements/moveables/Moveable.py
> +    def next_position(self, cur_position: tuple[int, int], direction: Direction) -> tuple[int, int]:
A tuple[] type-ot tartalmaznia kell a basic python3-nek.
Ahogy látszik is, nincs extra import vagy extension hivatkozva a modulokhoz.

2022-11-16 08:01 UTC, TothAron commented on SegmentFault/source/dynamic_elements/moveables/Moveable.py
> +    def next_position(self, cur_position: tuple[int, int], direction: Direction) -> tuple[int, int]:
Igen, köszi, látom. Megnéztem és Python 3.9-től van.

2022-11-16 18:49 UTC, DEW211 approved these changes
Szép munka! 🚀

2022-11-20 19:04 UTC, TothAron commented
Szép munka! Megvannak a docstring-ek, typing-ok. Érvényesülnek a clean code és SOLID elvek. Szépen fut a program. Gratulálok hozzá!

2022-11-21 09:39 UTC, merged