Pacman SOLID
bme-kjit/bosch_ASDIIE pull request #33
Opened 2022-11-11 14:40 UTC by Czeilinger96

Sziasztok, bocsi egy kicsit csúszott a PR.  Várom a reviewkat.

2022-11-13 00:41 UTC, gujgidani requested changes
Szia!

Átnéztem a kódodat. Első körben szeretném kiemelni, hogy nagyon tetszik a pygame-es megoldás. Vizualizáció szempontjából így sokkal tetszetősebb. A játék fut, a játékmenetben hibát nem találtam.

A kód struktúráját tekintve van néhány dolog, amin javítanék:
- Az egész játék 1 commitként került fel, ami nem a leginkább nyomonkövethető verziókezelés. Nyilván ezen változtatni már nem tudsz, de szerintem akár a későbbi munkásságod folyamán is hasznos lehet, ha 1 módosítás szerepel 1 commitban. Bár feltételezem, hogy ebben jelenleg az időfaktornak is szerepe volt. 😄 
- Mivel a kód 1 fájlban van megírva, így kissé nehezen áttekinthető (bár ez gondolom amiatt alakult így, mivel a korábbi kódodat alakítottad át a SOLID alapelvek szerint, nem pedig újrakezdted). A mintakód alapján az egyes osztályok kiszervezhetőek lennének külön fájlokba, ami esetleg könnyíthetne az áttekinthetőség és a megértés szempontjából. A kódban jelölt változtatási javaslatok mind 1 témát ölelnek fel: Ha egyes osztályokban hivatkozás történik másik osztályokra, akkor ezek használhatóak az adott osztály paramétereként. Ekkor azonban figyelni kell, hogy a hivatkozott osztályok korábban már definiálva legyenek. Erre szintén megoldást jelenthetne a külön fájlokba való kiszervezés.
- A kód ettől függetlenül a SOLID alapelveknek megfelelő, az egyes osztályok 1 dologért felelősek, valamint megvannak a szükséges interface-ek.
- Egy fontos észrevétel: Nincs **teszt** írva a kódhoz, ami szintén feladat a mostani sprintnél. Erre szerintem érdemes lenne figyelni, nehogy emiatt veszíts pontot. :sweat_smile:
- Egyéb helyen (a pygame mérsékelt ismerete miatt) a kódba nem kívánok belekötni.

A külön fájlokba kiszervezést, ha van még elég időd, szerintem érdemes átgondolni a korábbi szempontok miatt, bár ehhez lehet, hogy már túl későn szólok a merge előtt. Mindenesetre a teszt megírását mindenképp javaslom a szükséges feature-ök megléte miatt, a többi már csak szépség kérdése. :smiley:

Mindezt leszámítva, gratula a programhoz, szép munka (főleg, hogy egyedül írtad)! 😉 
UI: Bocsánat, ha kicsit hosszú voltam, próbáltam mindent indokolni 😅 

@Czeilinger96

2022-11-13 00:41 UTC, gujgidani commented on Pybranch/pacman.py
> +    def __init__(self) -> None:
Az egyes osztályoknál, ha egy másik osztályt is felhasználsz benne, szerintem érdemesebb ezeket az osztály paraméterévé tenni, ahogy a mintakódban is szerepelnek. Ebben az esetben például:
```suggestion
    def __init__(self,
                 collide: Collide,
                 bool: ListToBool) -> None:
        self.collide = collide
        self.bool = bool
```
Ehhez a jelenlegi kódstruktúra szerint szükség van arra, hogy mindig az egyes osztályok előtt definiáld azokat az osztályokat, amelyre az hivatkozik. Tehát ebben az esetben a Collide és a ListToBool osztályokat a DotCreator előtt kell létrehozni.

2022-11-13 00:41 UTC, gujgidani commented on Pybranch/pacman.py
> +    def __init__(self) -> None:
Osztályok paraméterként való használata (korábbi komment alapján).

2022-11-13 00:41 UTC, gujgidani commented on Pybranch/pacman.py
> +    def __init__(self) -> None:
Osztályok paraméterként való használata (korábbi komment alapján).

2022-11-13 00:41 UTC, gujgidani commented on Pybranch/pacman.py
> +    def __init__(self, left: int, top: int, width: int, height: int) -> None:
Osztályok paraméterként való használata (korábbi komment alapján).

2022-11-13 00:41 UTC, gujgidani commented on Pybranch/pacman.py
> +    def __init__(self) -> None:
Osztályok paraméterként való használata (korábbi komment alapján).

2022-11-13 00:41 UTC, gujgidani commented on Pybranch/pacman.py
> +    def __init__(self) -> None:
Osztályok paraméterként való használata (korábbi komment alapján).

2022-11-13 00:41 UTC, gujgidani commented on Pybranch/pacman.py
> +    def __init__(self) -> None:
Osztályok paraméterként való használata (korábbi komment alapján).

2022-11-13 00:41 UTC, gujgidani commented on Pybranch/pacman.py
> +    def __init__(self) -> None:
Osztályok paraméterként való használata (korábbi komment alapján).

2022-11-13 00:41 UTC, gujgidani commented on Pybranch/pacman.py
> +    def __init__(self) -> None:
Osztályok paraméterként való használata (korábbi komment alapján).

2022-11-13 00:41 UTC, gujgidani commented on Pybranch/pacman.py
> +    def __init__(self) -> None:
Osztályok paraméterként való használata (korábbi komment alapján).

2022-11-13 00:41 UTC, gujgidani commented on Pybranch/pacman.py
> +    def __init__(self) -> None:
Osztályok paraméterként való használata (korábbi komment alapján).

2022-11-14 10:52 UTC, szkLaszlo requested changes
Ez egy jó nagy fájl. Próbáld meg szétszedni logikai egységekre. Példákat láthatsz a többiben. Az előttem szólóhoz csatlakoznék. Keresd meg az egyes osztályok értelmét és csak akkor maradjanak ha tényleg van.

2022-11-14 14:04 UTC, benceuveges requested changes
Szia @Czeilinger96 !

A játék futásában én sem találtam hibát, nagyon jól néz ki a pygamenek köszönhetően és elismerésre méltó, hogy mindezt egyedül csináltad. Mint azt már személyesen is beszéltük, illetve az előttem szólók is kihangsúlyozták, érdemes lehet szétszedni a kódot kisebb komponensekre, illetve ha belefér az idődbe pótold a tesztet, hisz az is pontokat ér.
Azt hiszem @gujgidani mindent kiemelt, nem tudok újat mondani.

2022-11-14 20:24 UTC, 4doschris reviewed
Kedves @Czeilinger96!

@gujgidani már az elején "lelőtte a poént", de azért igyekszem leírni, hogy szerintem min lehetne javítani.

Maga a kód szép lett, ügyes megoldásokkal.
Ami viszont elsőre is szembetűnő volt, az nem más, mint hogy egyetlen nagy fájl az egész program, ez pedig nem szerencsés több szempontból sem.
- Mivel az osztályok nincsenek kiszervezve, az esetleges későbbi módosítások okozhatnak bonyodalmakat, mert így nehezen átlátható a több, mint 500 sornyi karaktersereg.
- Verziókövetés során erősen kellene gondolkodni, hogy hol történt a módosítás pl. valaki más által. Amennyiben kisebb commit-onként került volna fel az egész kód, egyből érthető lenne, hol történt módosítás.
Ez a kettő dolog erősen összefügg, így legközelebbre mindenképp javasolnám az egyes osztályok külön fájlokba, illetve commitokba rendezését.
A teszt ilyen formában talán nem is lehetséges, de mindenképp érdemes lenne egy kis időt ráfordítani, mert a végén az elszámolásnál is jól jönne az érte kapott néhány pont.

Ha jól értesültem, teljesen egyedül készítetted el a feladatot, minden elismerésem. Nyilván nem felel meg minden szempontnak a kód, ahogy talán egyikünké sem, de ez így is szép teljesítmény. 👏

2022-11-15 06:52 UTC, benceuveges approved these changes

2022-11-15 11:32 UTC, Czeilinger96 commented
Köszönöm a reviewkat. Amennyire tudtam szétszedtem kisebb fájlokra. Sajnos a test megírására nem nagyon maradt idő.

2022-11-15 22:15 UTC, gujgidani commented
@Czeilinger96 

Szia!

Szépen szét lettek szedve külön fájlokra az egyes részletek, így már sokkal jobban átlátható és érthető a kód. 

A jelölt change request-jeim viszont nem lettek megoldva. Az egyes osztályokban használt másik osztályok __init__ függvény paramétereként való megadása szerintem azért lenne hasznosabb, mivel ekkor az osztály létrehozásakor meg kell adni ezeket, így a paraméterek kívülről módosíthatóak lennének. Az első kommentemben jelöltem, hogy ezeket hogy gondolnám megvalósítani.

A teszteket pedig rád bízom. A mai gyakorlaton azt mondta Laci, hogy a hét végéig próbálja meg mindenki bemergelni a PR-jét. Saját szempontodból szerintem nem lenne érdemes veszni hagyni az ebből jövő pontokat. De ha erre tényleg nincs már időd, akkor ennek hiányában is el tudom fogadni a PR-t (ha a többi javaslatomra lett reagálva).😉

2022-11-18 20:31 UTC, gujgidani approved these changes
Szia!

Minden probléma megoldásra került, amit jelöltem, valamint a teszt is bekerült. A program változatlanul működik, így részemről mehet a merge. 😉 

Mégegyszer, gratula hozzá! 😁

2022-11-18 22:10 UTC, 4doschris approved these changes
Ahogy többiek írták, a módosítások megvannak, gratula! ;)

2022-11-21 09:30 UTC, szkLaszlo approved these changes
RÉszemről rendben :)

2022-11-21 09:39 UTC, merged