Git-egylet 3rd sprint: docker and code quality
bme-kjit/bosch_ASDIIE pull request #36
Opened 2022-12-04 16:58 UTC by gujgidani

Sziasztok!

Ebben a PR-ban a 3-ik sprint feladatai találhatóak, melyek a dockerrel és a code quality-val kapcsolatosak. Az esetleges észrevételeket szívesen látjuk. 

@szkLaszlo @Czeilinger96

2022-12-05 16:52 UTC, istvan-knab approved these changes
Megnéztem a dolgokat , a container működik , futtatásnál teszi a dolgát . Belenézegettem a radon_cc és radon_mi fileokba( Majdnem mindenhol csupa A 💪 ) , minden úgy van , ahogy lennie kell . Jó lesz így , szerintem ezzel további teendő nincsen 🔥

2022-12-10 18:41 UTC, BPelenczei requested changes
Sziasztok,

Szép eredmények jöttek ki a code quality measure-ökre, illetve jó lesz a docker setup is, légyszi a requirements-hez adjátok majd hozzá a radon lib-et (bár nyilván ezt is csak a szimuláció kedvéért).
Egyébként minden rendben, gratulálok!

Üdv,
Bálint

2022-12-10 18:41 UTC, BPelenczei commented on Git_egylet/docker/requirements.txt
> +argparse
itt még a radont tegyétek hozzá légyszi

2022-12-10 18:47 UTC, gujgidani commented on Git_egylet/docker/requirements.txt
> +argparse
Javítottam 😁

2022-12-10 18:50 UTC, BPelenczei approved these changes
Köszi, így már jó lesz, szép munka!

2022-12-10 19:46 UTC, Czeilinger96 approved these changes
Szép munka lett! Gratulálok!

2022-12-14 09:46 UTC, szkLaszlo approved these changes
Azt az egy kommentet leszámítva szép munka.

2022-12-14 09:46 UTC, szkLaszlo commented on Git_egylet/docker/requirements.txt
> +radon
Én verziókat is beletennék, hogy aki mondjuk két év múlva installálja, nehogy incompatibility legyen. :) De ez már csak egy good to know.

2022-12-14 12:25 UTC, merged