I_NEED_A  3.PR:  docker, code quality
bme-kjit/bosch_ASDIIE pull request #38
Opened 2022-12-04 21:15 UTC by TothAron

- added requirements.txt
- added Dockerfile
- docker build works
- added code quality results (cc, mi)

2022-12-05 16:53 UTC, istvan-knab commented
@markbozsoki @leonsuszter @origergelylaszlo @Amontobix elkészültünk , légyszi nézzétek át .  

Üdv : Isti

2022-12-05 20:16 UTC, Amontobix commented on I_NEED_A/docker/Dockerfile
> +ENTRYPOINT ["pip", "list"]
Szintaktikailag szerintem jó

2022-12-05 20:17 UTC, Amontobix commented on I_NEED_A/docker/radon_cc.txt
> +    C 4:0 KeyEvent - A
Szép osztályzatok

2022-12-05 20:21 UTC, Amontobix commented on I_NEED_A/docker/radon_mi.txt
> +pacman_solid/Objects/core/get_action.py - A
Itt is szép MI osztályzatok születtek

2022-12-05 20:30 UTC, Amontobix approved these changes
Sziasztok!

Szerintem nagyon jók lettek a metrikák, az előző review-k eredményeit szerintem tükrözik, szóval részemről rendben van, ha a többiek is elfogadják. 

Köszönöm a közös munkát!

Üdv.: Pali

2022-12-05 20:34 UTC, istvan-knab commented
> Sziasztok!
> 
> Szerintem nagyon jók lettek a metrikák, az előző review-k eredményeit szerintem tükrözik, szóval részemről rendben van, ha a többiek is elfogadják.
> 
> Köszönöm a közös munkát!
> 
> Üdv.: Pali

Köszönjük a gyors visszajelzést 😃

2022-12-06 00:40 UTC, markbozsoki requested changes
Nice
én kicsit jobban tagolnám a Dockerfile-t mondjuk
kommentezném is hogy melyik résznél mi fog történi, pl szükséges források másolása; ez-meg-az telepítése

2022-12-06 00:40 UTC, markbozsoki commented on I_NEED_A/docker/Dockerfile
> +COPY requirements.txt ./
Itt fel kéne másolni a teljes kódbázist is (egyszerű mappa másolást tud a docker)

2022-12-06 00:40 UTC, markbozsoki commented on I_NEED_A/docker/Dockerfile
> +RUN pip install radon
A radonnak pedig itt még kéne egy image-en belüli futtatás az előzetesen bemásolt kódbázison és utána kiírni az eredményeket

2022-12-10 10:29 UTC, istvan-knab commented on I_NEED_A/docker/Dockerfile
> +RUN pip install radon
@TothAron nálad ez meg van csinálva , légyszi orvosold hogy lássák , honnan vannak az értékek .

2022-12-10 10:55 UTC, markbozsoki commented on I_NEED_A/docker/Dockerfile
> +COPY requirements.txt ./
?

2022-12-10 10:57 UTC, istvan-knab commented on I_NEED_A/docker/Dockerfile
> +COPY requirements.txt ./
Elnézést , nem pusholtam , amint lesz lehetőségem orvoslom ezt is

2022-12-10 18:56 UTC, istvan-knab commented on I_NEED_A/docker/Dockerfile
> +COPY requirements.txt ./
Na most már tényleg ✅

2022-12-11 17:59 UTC, TothAron commented on I_NEED_A/docker/Dockerfile
> +RUN pip install radon
@markbozsoki Ki lettek javítva a dolgok, nézz rá kérlek. A Dockerfile-ban van példa, hogy hogyan kell buildelni megfelelően.

2022-12-11 18:43 UTC, markbozsoki requested changes
Na király, szerintem ez így mehetne is fel, ha a .idea mappák nem kerültek volna fel :/
Mindkét .idea mappa legyen törölve és megy is az approve

2022-12-11 18:49 UTC, markbozsoki approved these changes
Zseni 💯

2022-12-11 18:55 UTC, origergelylaszlo approved these changes
Részemről is mindent rendben találtam, gratulálok.

2022-12-11 19:24 UTC, gujgidani requested changes
Sziasztok! Egy apróbb, kevésbé lényeges hibát találtam (felesleges kódrészlet). Ezt jelöltem is a kommentemben. Ezt leszámítva szép munka, gratula hozzá! 😁 Ha ez kijavításra kerül, részemről nincs akadálya a merge-nek. 😄

2022-12-11 19:24 UTC, gujgidani commented on I_NEED_A/docker/requirements.txt
> +gym == 0.26.2
Itt szükség van a yaml-ra, a torch-ra és a gym-re? A kódotokban nem igazán látok olyan részt, ahol használva lennének ezek a könyvtárak 😅

2022-12-11 19:50 UTC, istvan-knab commented on I_NEED_A/docker/requirements.txt
> +gym == 0.26.2
Javítottam , köszi az észrevételt.

2022-12-11 19:51 UTC, gujgidani approved these changes

2022-12-11 19:52 UTC, istvan-knab commented
Köszi az észrevételt @gujgidani 🚀

2022-12-14 09:47 UTC, szkLaszlo approved these changes

2022-12-14 09:47 UTC, merged